// Sends a new fencing company FenceFlow's welcome email -- once, ever.
//
// WHO CALLS IT: one thing only, the companies_queue_welcome_email trigger in
// supabase_r6_welcome_email.sql, through pg_net. It fires the moment a
// company first has BOTH its details completed (welcome.html's first step,
// which every signup path goes through -- invitation, setup code, or signing
// up on the office) AND a way in: a subscription from Stripe checkout, or a
// trial the admin started. That is the moment the office opens for them
// (company_allowed()), so "Open your office" leads somewhere real, and it
// catches every path without welcome.html, the office or stripe-webhook
// having to remember to call anything.
//
// THE DOOR: the trigger sends a secret it reads from Vault
// (welcome_email_trigger_secret, generated by the migration, never printed)
// in x-fenceflow-welcome. This function checks it through
// welcome_email_trigger_ok(), which only the service role may call, before it
// reads the body or anything else. verify_jwt is off in config.toml because a
// database trigger has no user session; this check is what replaces it. Even
// a caller holding the secret can only ever cause the one welcome email, to
// the company's own owner, once: the recipient and every word come from the
// database, never from the request.
//
// EXACTLY ONCE: the company is claimed with
//   update companies set welcome_sent_at = now()
//    where id = $1 and welcome_sent_at is null returning id
// and the email goes only if a row came back. Two triggers racing, a pg_net
// retry, anything -- one of them gets the row, the rest get nothing to do.
// If the provider refuses the send outright (4xx: certainly not sent), the
// claim is released so the column stays true to what went out. On a 5xx or
// no answer at all the claim stays: "maybe not sent" beats "sent twice", the
// same rule send-follow-ups follows. Nothing retries it automatically; the
// log line says what happened.
//
// NOT SENT TO: a test company (a name starting "ZZ TEST", the same convention
// supabase_test_companies.sql and the job fixtures use), a company with no
// owner or an owner with no email, or one that is not ready after all (the
// trigger's judgement is re-checked here, never trusted).
//
// Mail goes through the same provider and secrets as invite-company
// (MAIL_API_KEY, MAIL_FROM, MAIL_API_URL, MAIL_FROM_NAME), from FenceFlow
// itself, with replies going to support. No address is written to the logs.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.0";
import { buildWelcomeEmail } from "../_shared/welcome-email.ts";

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json" } });

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
// encode(gen_random_bytes(32), 'hex') in the migration: 64 hex characters.
// Anything else is refused before the database is asked about it.
const SECRET_RE = /^[0-9a-f]{64}$/;

/** "FenceFlow <x@y>" -- the same sanitising as invite-crew's senderWithName:
 *  the bare address when MAIL_FROM already carries a display name. */
function senderWithName(name: string, address: string): string {
  const clean = name.replace(/[\r\n<>"]/g, "").trim().slice(0, 70);
  if (!clean || address.includes("<")) return address;
  return `"${clean}" <${address}>`;
}

/** The same readiness the trigger checks: details done, and a way in. */
function ready(c: {
  details_completed_at: string | null;
  stripe_subscription_id: string | null;
  subscription_status: string | null;
  trial_ends_at: string | null;
}): boolean {
  return !!c.details_completed_at && (
    !!c.stripe_subscription_id ||
    c.subscription_status === "active" ||
    c.subscription_status === "trialing" ||
    !!c.trial_ends_at
  );
}

Deno.serve(async (req) => {
  if (req.method !== "POST") return json({ error: "method not allowed" }, 405);

  let companyId = "";
  const log = (outcome: string, extra: Record<string, unknown> = {}) =>
    console.log(JSON.stringify({ fn: "send-welcome-email", outcome, company: companyId || null, ...extra }));

  try {
    const admin = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    );

    // The door, before anything else is read.
    const supplied = (req.headers.get("x-fenceflow-welcome") ?? "").trim();
    if (!SECRET_RE.test(supplied)) return json({ error: "unauthorized" }, 401);
    const { data: allowed, error: allowErr } = await admin.rpc("welcome_email_trigger_ok", { p_secret: supplied });
    if (allowErr) {
      log("error", { stage: "door", reason: allowErr.message });
      return json({ error: "could not check the caller" }, 500);
    }
    if (allowed !== true) return json({ error: "unauthorized" }, 401);

    const body = await req.json().catch(() => ({}));
    companyId = String(body?.company_id ?? "").trim();
    if (!UUID_RE.test(companyId)) {
      companyId = "";
      return json({ error: "bad request" }, 400);
    }

    const mailKey = Deno.env.get("MAIL_API_KEY");
    const mailFrom = Deno.env.get("MAIL_FROM");
    const mailUrl = Deno.env.get("MAIL_API_URL") ?? "https://api.resend.com/emails";
    const fromName = Deno.env.get("MAIL_FROM_NAME") ?? "FenceFlow";
    const site = (Deno.env.get("SITE_URL") ?? "https://fenceflowapp.com").replace(/\/+$/, "");
    const support = Deno.env.get("SUPPORT_EMAIL") ?? "support@fenceflowapp.com";
    if (!mailKey || !mailFrom) {
      // Nothing claimed, so nothing is lost but this one email.
      log("not_configured");
      return json({ error: "mail not configured" }, 503);
    }

    const { data: company, error: coErr } = await admin
      .from("companies")
      .select("id, name, details_completed_at, welcome_sent_at, subscription_plan, subscription_status, stripe_subscription_id, trial_ends_at")
      .eq("id", companyId)
      .maybeSingle();
    if (coErr) {
      log("error", { stage: "company", reason: coErr.message });
      return json({ error: "could not read the company" }, 500);
    }
    if (!company) { log("skipped", { reason: "no such company" }); return json({ skipped: "no such company" }); }
    if (company.welcome_sent_at) { log("skipped", { reason: "already sent" }); return json({ skipped: "already sent" }); }
    if (!ready(company)) { log("skipped", { reason: "not ready" }); return json({ skipped: "not ready" }); }
    if (/^\s*zz test/i.test(String(company.name ?? ""))) {
      log("skipped", { reason: "test company" });
      return json({ skipped: "test company" });
    }

    // The owner who signed up -- the first OWNER on the company -- at the
    // address their login uses. Never the company's typed contact email: that
    // is a field the owner can set to anything, and this is FenceFlow's own
    // domain sending.
    const { data: owner, error: ownerErr } = await admin
      .from("profiles")
      .select("id, full_name")
      .eq("company_id", companyId)
      .eq("role", "OWNER")
      .order("created_at", { ascending: true })
      .limit(1)
      .maybeSingle();
    if (ownerErr) {
      log("error", { stage: "owner", reason: ownerErr.message });
      return json({ error: "could not read the owner" }, 500);
    }
    if (!owner) { log("skipped", { reason: "no owner" }); return json({ skipped: "no owner" }); }
    const { data: account, error: accountErr } = await admin.auth.admin.getUserById(owner.id);
    if (accountErr) {
      log("error", { stage: "account", reason: accountErr.message });
      return json({ error: "could not read the owner's account" }, 500);
    }
    const to = String(account?.user?.email ?? "").trim();
    if (!to) { log("skipped", { reason: "owner has no email" }); return json({ skipped: "owner has no email" }); }

    // The claim. Only the caller that gets the row back sends.
    const { data: claimed, error: claimErr } = await admin
      .from("companies")
      .update({ welcome_sent_at: new Date().toISOString() })
      .eq("id", companyId)
      .is("welcome_sent_at", null)
      .select("id");
    if (claimErr) {
      log("error", { stage: "claim", reason: claimErr.message });
      return json({ error: "could not claim the company" }, 500);
    }
    if (!claimed || claimed.length === 0) {
      log("skipped", { reason: "already sent" });
      return json({ skipped: "already sent" });
    }

    const email = buildWelcomeEmail({
      companyName: String(company.name ?? ""),
      ownerName: String(owner.full_name ?? ""),
      recipientEmail: to,
      plan: company.subscription_plan,
      officeUrl: `${site}/dashboard.html`,
      supportEmail: support,
    });

    let res: Response;
    try {
      res = await fetch(mailUrl, {
        method: "POST",
        headers: { Authorization: `Bearer ${mailKey}`, "Content-Type": "application/json" },
        body: JSON.stringify({
          from: senderWithName(fromName, mailFrom),
          to: [to],
          reply_to: support,
          subject: email.subject,
          html: email.html,
          text: email.text,
        }),
      });
    } catch (_e) {
      // No answer: it may have gone out, so the claim stays.
      log("error", { stage: "send", reason: "no answer from the mail provider" });
      return json({ error: "could not reach the mail provider" }, 502);
    }

    if (!res.ok) {
      const detail = (await res.text().catch(() => "")).slice(0, 300);
      if (res.status >= 400 && res.status < 500) {
        // Refused outright, so certainly not sent: give the claim back.
        await admin.from("companies").update({ welcome_sent_at: null }).eq("id", companyId);
      }
      log("refused", { status: res.status, detail });
      return json({ error: `mail provider answered ${res.status}` }, 502);
    }

    const sent = await res.json().catch(() => ({}));
    log("sent", { provider_id: sent?.id ? String(sent.id) : null });
    return json({ sent: true });
  } catch (e) {
    log("error", { stage: "unexpected", reason: String(e instanceof Error ? e.message : e) });
    return json({ error: "unexpected error" }, 500);
  }
});
