// Nudges the ONE phone that just lost this login to go and ask the server
// whether it still holds it.
//
// WHO CALLS IT: one thing only, the profiles_push_displaced_device trigger in
// supabase_r9_displaced_device_push.sql, through pg_net. It fires when
// claim_device moves profiles.active_device_id from one handset to another --
// a sign-in on a new phone, or "Use this phone" on the signed-in-elsewhere
// screen -- and sends the OLD install id.
//
// WHAT IT SENDS: a data message carrying one field, kind=device_displaced.
// No words. No verdict. No company name, no job, no amount, nothing about the
// phone that took over.
//
// WHAT THE PHONE IS EXPECTED TO DO WITH IT: call device_still_mine itself and
// believe only that (notify/DeviceClaimPush.kt). The push is a nudge to ask,
// never the answer. That is not decoration: this function's door is a shared
// secret, and if the message carried the verdict then anybody who ever got hold
// of that secret could sign a working crew out of the app from a dead spot.
// Because the phone re-asks, the worst a forged message can do is make one
// handset spend one request confirming what it already believed.
//
// WHY IT CANNOT LOCK ANYBODY OUT: it has no way to write active_device_id and
// does not try. The only code that sets a phone's displaced flag is
// ServiceGate.stillMine, which is documented to fail OPEN -- "Only ever false on
// a definite answer from the server. Offline, or any failure, leaves it true --
// a crew member in a dead spot must not be thrown out of the app on a guess."
// This function is upstream of that sentence and changes nothing about it.
//
// THE DOOR: the trigger reads a secret from Vault
// (displaced_device_trigger_secret, generated by the migration, never printed)
// and sends it in x-fenceflow-displaced. This function checks it through
// displaced_push_ok(), which only the service role may call, before it reads
// the body. Same shape as send-welcome-email. verify_jwt is off in config.toml
// because a database trigger has no user session; this check is what replaces
// it.
//
// ONE PHONE, NOT A FAN-OUT: the lookup is device_tokens rows whose user_id AND
// device_id match what the trigger sent. Not every device on the account, not
// the company. The other senders in this project go through
// _shared/push-recipients.ts because they carry job and money words that only
// some people may see; this one carries no words at all, and its recipient is
// named by the database write that caused it rather than worked out from
// permissions, so borrowing that machinery would add a permission question
// where there is nothing to permit.
//
// NOT ADDRESSED BY COMPANY, and that is a deliberate departure from
// push-recipients.ts's "Both filters, always" rule. That rule protects company
// words from reaching a phone whose device row still carries an old employer.
// There are no words here. Filtering on a company stamp that can be stale could
// only cause the stop signal to be MISSED, which is the exact failure this
// function exists to remove. company_id is read from the body for the log line
// and is never a filter.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.0";
import { accessToken, sendData } from "./fcm.ts";

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json" } });

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
// encode(gen_random_bytes(32), 'hex') in the migration: 64 hex characters.
// Anything else is refused before the database is asked about it.
const SECRET_RE = /^[0-9a-f]{64}$/;

/**
 * The one field the phone reads. Kept as a named constant on both sides --
 * notify/DeviceClaimPush.kt PUSH_KIND holds the same word -- because a typo
 * here is a message the phone quietly treats as an ordinary notification with
 * no body and drops.
 */
const KIND = "device_displaced";

Deno.serve(async (req) => {
  if (req.method !== "POST") return json({ error: "method not allowed" }, 405);

  let company = "";
  const log = (outcome: string, extra: Record<string, unknown> = {}) =>
    console.log(JSON.stringify({ fn: "notify-device-displaced", outcome, company: company || null, ...extra }));

  try {
    const admin = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    );

    // The door, before the body is read.
    const supplied = (req.headers.get("x-fenceflow-displaced") ?? "").trim();
    if (!SECRET_RE.test(supplied)) return json({ error: "unauthorized" }, 401);
    const { data: allowed, error: doorErr } = await admin.rpc("displaced_push_ok", { p_secret: supplied });
    if (doorErr) {
      log("error", { stage: "door", reason: doorErr.message });
      return json({ error: "could not check the caller" }, 500);
    }
    if (allowed !== true) return json({ error: "unauthorized" }, 401);

    const body = await req.json().catch(() => ({}));
    const userId = String(body?.user_id ?? "").trim();
    const oldDeviceId = String(body?.old_device_id ?? "").trim();
    company = String(body?.company_id ?? "").trim();
    if (!UUID_RE.test(userId)) return json({ error: "bad request" }, 400);
    // ServiceGate writes a uuid, but the column is text and older or
    // hand-edited rows need not be one. Length is the only thing worth
    // insisting on: something has to be there, and it must not be an essay.
    if (!oldDeviceId || oldDeviceId.length > 200) return json({ error: "bad request" }, 400);

    // The trigger's judgement, re-checked rather than trusted -- the same
    // discipline send-welcome-email follows with its readiness test.
    //
    // pg_net can retry, and a claim can be undone by the other phone tapping
    // "Use this phone" back a second later. Without this, a late or duplicated
    // message would nudge the handset that now legitimately HOLDS the login.
    // That would cost nothing worse than one wasted device_still_mine call,
    // because the phone re-asks -- but a message sent on a fact that is no
    // longer true is exactly the kind of thing that later gets trusted.
    const { data: profile, error: profileErr } = await admin
      .from("profiles").select("active_device_id").eq("id", userId).maybeSingle();
    if (profileErr) {
      log("error", { stage: "profile", reason: profileErr.message });
      return json({ error: "could not read the account" }, 500);
    }
    if (!profile) { log("skipped", { reason: "no such account" }); return json({ skipped: "no such account" }); }
    if (profile.active_device_id === oldDeviceId) {
      log("skipped", { reason: "that phone holds the login again" });
      return json({ skipped: "that phone holds the login again" });
    }

    const raw = Deno.env.get("FIREBASE_SERVICE_ACCOUNT");
    if (!raw) {
      // Nothing is worse off than before: the phone still finds out on its
      // next resume, which is what happened every time until now.
      log("not_configured");
      return json({ error: "push not configured" }, 503);
    }
    const sa = JSON.parse(raw);

    // That one handset. Normally one row; it can be more than one when the same
    // install has been issued a new FCM token and the old row has not been
    // cleaned up yet, and every one of those rows is still THIS phone.
    const { data: rows, error: devErr } = await admin
      .from("device_tokens").select("token")
      .eq("user_id", userId).eq("device_id", oldDeviceId);
    if (devErr) {
      log("error", { stage: "device_tokens", reason: devErr.message });
      return json({ error: "could not read the device" }, 500);
    }
    if (!rows?.length) {
      // The ordinary case for a phone on a build from before the install id was
      // recorded, and for one that has not been opened with a live session
      // since. It is not a fault and it is not silent: this line says how often
      // it happens, and that phone behaves exactly as it does today.
      log("skipped", { reason: "that handset has never registered an install id", device: oldDeviceId });
      return json({ skipped: "no token for that device" });
    }

    const bearer = await accessToken(sa);
    const stale: string[] = [];
    let sent = 0;
    for (const r of rows) {
      // One field. No words: the phone writes its own, in its own language,
      // and only after the server has confirmed it.
      const outcome = await sendData(r.token, sa.project_id, bearer, { kind: KIND });
      if (outcome.stale) stale.push(r.token);
      else if (outcome.ok) sent++;
      else log("send_failed", { status: outcome.status });
    }
    if (stale.length) await admin.from("device_tokens").delete().in("token", stale);

    log("done", { sent, dropped: stale.length });
    return json({ sent, dropped: stale.length });
  } catch (e) {
    console.error(JSON.stringify({ fn: "notify-device-displaced", outcome: "error", reason: String(e) }));
    return json({ error: String(e) }, 500);
  }
});
