-- SUPERSEDED. DO NOT RUN THIS FILE. The fix already existed:
--
--     supabase_r11_time_entry_rate_permission.sql
--
-- Kept as a tombstone rather than deleted, because what it got wrong is the
-- thing the next person will get wrong too.
--
-- ############################################################################
-- WHAT THIS FILE ORIGINALLY CONTAINED, AND WHY IT WAS DANGEROUS
--
-- tests/a4-labour.test.mjs reports, correctly, that a SALES account could write
-- a fabricated payroll figure: stamp_time_entry_rate() decides whether to keep
-- a submitted hourly_rate by asking can_see_pay(), and can_see_pay() resolves
-- to has_permission('SEE_MONEY'), which SALES holds.
--
-- I read that as "a function named for SEE_PAY is asking for SEE_MONEY" and
-- narrowed can_see_pay() to SEE_PAY. That is wrong, and this repo has already
-- paid for it once: supabase_can_see_pay_restored.sql exists purely to undo the
-- identical change, made and reverted the same day. Its first line:
--
--     "Undoing a change I made three hours ago that would have taken every
--      salesperson's phone dark."
--
-- can_see_pay() is badly named. It is not the payroll question. The Android
-- client asks it ONCE per sync pass and uses the answer as its ENTIRE money
-- scope -- job pricing, tax, markup, deposits, payments, line item costs,
-- catalog prices, pricing tiers. SyncScope.kt, askMoneyScope(), literally
-- `rpc("can_see_pay")`.
--
-- So on the next sync of any SALES phone: SEE_MONEY yes, SEE_PAY no, scope
-- DENIED, AutoSync calls forgetMoney() and resets that phone's cached job money
-- to defaults -- while the pricing screen, gated on a separate local SEE_MONEY
-- check, carries on displaying it. No error. A zero markup and a zero deposit
-- that look like real figures, on a quote being handed to a customer.
--
-- I dry-ran the change and recommended it. The dry run proved only that the
-- function still compiled and that the one role I expected had changed. It
-- never asked what else calls can_see_pay(). A read-only `grep -rn can_see_pay`
-- across the app would have found SyncScope.kt in seconds.
--
-- THE LESSON, which is the only reason this file still exists: before changing
-- a shared predicate, enumerate its CALLERS, not just its behaviour. A function
-- whose name no longer matches its job is exactly the one where that matters
-- most, and a comment in a nearby file may already be telling you so.
-- ############################################################################
--
-- THE ACTUAL FIX, already written before I started:
--
-- supabase_r11_time_entry_rate_permission.sql changes the one faulty CALLER
-- instead of the shared function. stamp_time_entry_rate() asks
-- can_see_employee_pay() (SEE_PAY, the correctly-named payroll helper that
-- supabase_can_see_pay_restored.sql created for precisely this) and
-- can_see_pay() is left alone, so nothing about the phone's money scope moves.
--
-- Confirmed live on 5 Oct 2026, read-only:
--   can_see_employee_pay() exists and tests SEE_PAY            -> true
--   stamp_time_entry_rate() still calls can_see_pay()          -> true
--   stamp_time_entry_rate() calls can_see_employee_pay()       -> false
--
-- So r11 is written and NOT applied. Applying it is what makes a4-labour go
-- green, and a4-labour must never be edited to go green instead.
--
-- Nothing is forcing it today: the only SALES profile on this database has a
-- null company_id, so the company-scoped insert policy refuses it. It wants to
-- go in before a real SALES user is created inside a company.

-- (no statements -- deliberately. Run supabase_r11_time_entry_rate_permission.sql.)
