// tests/a29-deposit-and-rounding.test.mjs
//
// 1 Oct 2026. Two decisions the owner took, knowing what each costs:
//
//   1. THE TOTAL IS EXACT. grand_total used to be ceil(max(afterDiscount,
//      minimumJobCharge) / 10) * 10. It is now roundToCents(...): the same
//      figure to the cent, in both engines, with the engine version bumped.
//   2. THE DEPOSIT is the materials still to be bought, rounded UP to the next
//      $100, plus another $100 -- never more than is still owed. The extra
//      $100 is not disclosed to the customer.
//
// What this file holds, and what it deliberately does not:
//   - the shared vectors (tests/a29-deposit-rule-vectors.json) against the
//     TypeScript side. Kotlin runs the SAME file in JobMoneyDepositRuleTest.kt;
//   - the engine, run for real (priceJob), exact to the cent, with the minimum
//     job charge reading exactly the minimum;
//   - quote-view's own fallback total, run for real against a fake database;
//   - the version, on both sides, pinned equal and moved;
//   - that the quote page never adds the extra hundred itself.
// It does NOT replay the parity fixtures. Those are regenerated by the gate,
// after a clean test compile, and not here.
//
// Every rule has a planted failure beside it: the figure the OLD behaviour
// gives for the same input, asserted to differ, so a test that would pass
// whichever rule ran cannot hide in here.
//
// Run with: node --test tests/a29-deposit-and-rounding.test.mjs

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { stripTypeScriptTypes } from "node:module";
import * as quoteDeposit from "../supabase/functions/_shared/quote-deposit.ts";
import * as jobPush from "../supabase/functions/_shared/job-push.ts";
import * as pushRecipients from "../supabase/functions/_shared/push-recipients.ts";
import { priceJob, PRICING_ENGINE_VERSION } from "../supabase/functions/_shared/pricing/index.ts";
import { roundToCents as engineRoundToCents } from "../supabase/functions/_shared/pricing/totals.ts";

const { roundToCents, ruleDeposit, suggestedDeposit, depositFigures, DEPOSIT_ROUND_UP_TO, DEPOSIT_PLUS } = quoteDeposit;

const read = (p) => readFileSync(new URL(`../${p}`, import.meta.url), "utf8");
const vectors = JSON.parse(read("tests/a29-deposit-rule-vectors.json"));

// What the engine did before 1 Oct 2026, for the planted failures.
const oldCeilTen = (x) => Math.ceil(x / 10) * 10;
const oldTenDeposit = (outstanding) => Math.ceil(outstanding / 10) * 10;

// ============================================================ rounding ====

test("roundToCents: every shared vector, through BOTH TypeScript copies (the page's and the engine's)", () => {
  assert.ok(vectors.roundToCents.length >= 10, "the vector file lost its rows");
  for (const v of vectors.roundToCents) {
    assert.equal(roundToCents(v.in), v.out, `${v.name}: quote-deposit roundToCents(${v.in})`);
    assert.equal(engineRoundToCents(v.in), v.out, `${v.name}: pricing/totals roundToCents(${v.in})`);
  }
  for (const bad of [NaN, Infinity, -Infinity]) {
    assert.ok(Object.is(engineRoundToCents(bad), roundToCents(bad)), `non-finite ${bad}`);
  }
});

test("PLANTED: the old round-up-to-ten gives a different answer for almost every vector", () => {
  // If this stopped differing, the vectors above would pass under either rule.
  const differing = vectors.roundToCents.filter((v) => v.in > 0 && oldCeilTen(v.in) !== v.out);
  assert.ok(differing.length >= 8, `only ${differing.length} vectors tell the two rules apart`);
  assert.equal(oldCeilTen(2114.633), 2120);
  assert.equal(roundToCents(2114.633), 2114.63);
});

test("roundToCents leaves a non-finite value visibly broken instead of turning NaN into $0", () => {
  assert.ok(Number.isNaN(roundToCents(NaN)));
  assert.equal(roundToCents(Infinity), Infinity);
  assert.equal(roundToCents(-Infinity), -Infinity);
});

test("roundToCents is idempotent, so rounding an already-exact total changes nothing", () => {
  for (const v of vectors.roundToCents) {
    assert.equal(roundToCents(roundToCents(v.in)), roundToCents(v.in), v.name);
  }
});

// ================================================================ engine ==

const CATALOG = [];
const job = (o = {}) => ({
  calibration_pixels_per_foot: null,
  tax_rate_percent: 0, markup_percent: 0, discount_percent: 0,
  labor_rate_per_ft: 0, labor_flat_fee: 0, minimum_job_charge: 0, minimum_labor_charge: 0,
  waste_percent: 0, gate_rate_per_ft: 0, trash_haul_fee: 0,
  teardown_enabled: false, teardown_flat_fee: 0, teardown_rate_per_ft: 0, teardown_feet: 0,
  preferred_manufacturer_sync_id: null, ...o,
});
const run = (id) => ({
  sync_id: id, label: id, fence_type: "VINYL", color_or_finish: "", points_encoded: "", gates_encoded: "",
  closed_loop: false, manual_linear_feet: 4, manual_corner_count: 0, panel_width_ft: 6, panel_height_ft: 6,
  post_spacing_ft: 6, concrete_bags_per_post: 1, aluminum_style: "RACKABLE", wood_style: "PRIVACY",
  wood_rail_count: 3, picket_width_in: 5.5, picket_gap_in: 0, fabric_height_ft: 4, include_top_rail: true,
  include_tension_wire: false, include_barbed_wire_arms: false, include_privacy_slats: false, split_rail_count: 2,
  // Every role the run would build is suppressed: the lump-sum lines below are the whole job.
  suppressed_roles: "PANEL,LINE_POST,END_POST,CORNER_POST,POST_CAP,CONCRETE_BAG", is_teardown: false, sort_order: 0,
});
const lump = (id, price, taxable = false) => ({
  sync_id: id, fence_run_sync_id: null, role: "NONE", description: id, quantity: 1, unit: "EA",
  unit_price: price, supplier_unit_price: null, taxable, auto_generated: false, sort_order: 0,
});
const price = (jobOverrides, lines) => priceJob({
  engine_version: PRICING_ENGINE_VERSION, pixels_per_foot: 20, job: job(jobOverrides),
  runs: [run("r")], catalog: CATALOG, manufacturers: [], change_orders: [], existing_items: lines,
}).totals.grand_total;

test("engine: the total is exact to the cent, not rounded up to the next ten", () => {
  assert.equal(price({}, [lump("a", 2113.01)]), 2113.01);
  assert.equal(oldCeilTen(2113.01), 2120, "PLANTED: the old rule said 2120 for this job");
});

test("engine: float dust is cleaned to cents, not stored (1000 + 1269.32)", () => {
  assert.notEqual(1000 + 1269.32, 2269.32, "precondition: the double sum really is dust");
  assert.equal(price({}, [lump("a", 1000), lump("b", 1269.32)]), 2269.32);
});

test("engine: tax, markup and discount still compose, and only the final figure is rounded", () => {
  // 1000 taxable at 7% = 1070; +12% markup = 1198.4; -5% = 1138.48 exactly.
  assert.equal(price({ tax_rate_percent: 7, markup_percent: 12, discount_percent: 5 }, [lump("a", 1000, true)]), 1138.48);
});

test("engine: a job at the minimum job charge reads exactly the minimum", () => {
  assert.equal(price({ minimum_job_charge: 450 }, [lump("a", 183.47)]), 450);
  assert.equal(price({ minimum_job_charge: 450 }, [lump("a", 450)]), 450);
  assert.equal(price({ minimum_job_charge: 450 }, []), 450, "nothing on the job at all still reads the minimum");
  // And a job above it is not pulled to it.
  assert.equal(price({ minimum_job_charge: 450 }, [lump("a", 451.23)]), 451.23);
});

test("engine: a minimum typed with a stray fraction is still a figure on cents", () => {
  assert.equal(price({ minimum_job_charge: 450.004 }, [lump("a", 10)]), 450);
});

test("engine: the minimum labour charge still floors labour (it never took part in the old rounding)", () => {
  // 180 materials + 4 ft at 8 = 32 floored to 200 labour = 380.
  assert.equal(price({ labor_rate_per_ft: 8, minimum_labor_charge: 200 }, [lump("a", 180)]), 380);
});

// ================================================================ version ==

const kotlinVersion = /const val PRICING_ENGINE_VERSION = "([^"]+)"/.exec(read("app/src/main/java/com/fenceestimator/app/estimate/EstimateEngine.kt"))?.[1];
const versionIsNewer = (a, b) => {
  const x = a.split(".").map(Number), y = b.split(".").map(Number);
  for (let i = 0; i < Math.max(x.length, y.length); i++) if ((x[i] ?? 0) !== (y[i] ?? 0)) return (x[i] ?? 0) > (y[i] ?? 0);
  return false;
};

test("version: Kotlin and TypeScript carry the SAME engine version", () => {
  assert.ok(kotlinVersion, "could not read PRICING_ENGINE_VERSION out of EstimateEngine.kt");
  assert.equal(PRICING_ENGINE_VERSION, kotlinVersion);
});

test("version: the rounding is a formula change, so the version moved off 2026.09.3", () => {
  assert.notEqual(PRICING_ENGINE_VERSION, "2026.09.3");
  assert.ok(versionIsNewer(PRICING_ENGINE_VERSION, "2026.09.3"),
    "JobSync.engineVersionIsNewer compares component by component: the bump must be NEWER or an old office row reads as ahead of the phone");
  // 2026.10.1 against 2026.09.3: component two is 10 vs 9, which a string compare of "2026.10.1" < "2026.9.3" would get backwards.
  assert.ok(versionIsNewer("2026.10.1", "2026.9.3"));
});

// ================================================== the rounding is gone ==

/** Source with comments removed, so a check reads the code and not the history written beside it. */
const code = (src) => src.replace(/\/\*[\s\S]*?\*\//g, "").replace(/(^|[^:])\/\/[^\n]*/g, "$1");

test("source: neither engine rounds the total up to ten any more", () => {
  const ts = code(read("supabase/functions/_shared/pricing/totals.ts"));
  const kt = code(read("app/src/main/java/com/fenceestimator/app/estimate/EstimateEngine.kt"));
  assert.match(ts, /const grandTotal = roundToCents\(Math\.max\(afterDiscount, job\.minimumJobCharge\)\);/);
  assert.match(kt, /val grandTotal = roundToCents\(maxOf\(afterDiscount, job\.minimumJobCharge\)\)/);
  assert.doesNotMatch(ts, /Math\.ceil\(Math\.max\(afterDiscount/);
  assert.doesNotMatch(kt, /ceil\(maxOf\(afterDiscount/);
  // PLANTED: the regexes above do bite on the old line.
  const oldTs = "const grandTotal = Math.ceil(Math.max(afterDiscount, job.minimumJobCharge) / 10.0) * 10.0;";
  assert.match(oldTs, /Math\.ceil\(Math\.max\(afterDiscount/);
});

test("source: the quote page's own fallback no longer rounds up to ten", () => {
  const src = code(read("supabase/functions/quote-view/index.ts"));
  assert.match(src, /roundToCents\(subtotal \+ tax\)/);
  assert.doesNotMatch(src, /Math\.ceil\(\(subtotal \+ tax\) \/ 10\)/);
});

test("source: the two languages round to cents the same way", () => {
  const kt = read("app/src/main/java/com/fenceestimator/app/estimate/EstimateEngine.kt");
  assert.match(kt, /Math\.round\(value \* 100\.0\) \/ 100\.0/);
  assert.match(read("supabase/functions/_shared/quote-deposit.ts"), /Math\.round\(value \* 100\) \/ 100/);
  // kotlin.math.round would round half to even and disagree with the server.
  assert.doesNotMatch(code(kt), /fun roundToCents[^\n]*kotlin\.math\.round/);
});

// =============================================================== deposit ==

test("deposit rule: every shared vector", () => {
  assert.ok(vectors.ruleDeposit.length >= 15, "the vector file lost its rows");
  for (const v of vectors.ruleDeposit) assert.equal(ruleDeposit(v.outstanding), v.out, `ruleDeposit(${v.outstanding})`);
});

test("deposit rule: rounded up to the next hundred, then a hundred more -- in one sentence of arithmetic", () => {
  assert.equal(DEPOSIT_ROUND_UP_TO, 100);
  assert.equal(DEPOSIT_PLUS, 100);
  assert.equal(ruleDeposit(1630), 1800);
  assert.equal(ruleDeposit(1000), 1100, "an exact hundred stays where it is before the $100 is added");
  assert.equal(ruleDeposit(1000.01), 1200);
});

test("PLANTED: the old ten-dollar suggestion differs from the rule on every vector", () => {
  for (const v of vectors.ruleDeposit.filter((r) => r.out > 0)) {
    assert.notEqual(oldTenDeposit(v.outstanding), v.out, `old rule gave the same answer for ${v.outstanding}`);
  }
});

test("deposit rule: float dust does not push a deposit into the next hundred", () => {
  assert.equal(ruleDeposit(1000.0000000000001), 1100);
  assert.equal(ruleDeposit(999.9999999999999), 1100);
  // PLANTED: without taking cents first, a bare ceil jumps a whole hundred on 1e-13 of dust.
  assert.equal(Math.ceil(1000.0000000000001 / 100) * 100 + 100, 1200);
});

test("deposit rule: a deposit is never negative, and non-numbers are nothing", () => {
  assert.equal(ruleDeposit(-1), 0);
  assert.equal(ruleDeposit(NaN), 0);
  assert.equal(ruleDeposit(Infinity), 0);
  assert.equal(ruleDeposit(undefined), 0);
});

test("suggested deposit: every shared vector", () => {
  assert.ok(vectors.suggestedDeposit.length >= 12, "the vector file lost its rows");
  for (const v of vectors.suggestedDeposit) {
    const got = suggestedDeposit(v);
    assert.deepEqual(got, { amount: v.amount, capped: v.capped }, v.name);
  }
});

test("suggested deposit: the cap is the existing one, and on a small job the customer sees the whole job, not more", () => {
  const small = suggestedDeposit({ materialCost: 120, amountPaid: 0, refundedAmount: 0, billableTotal: 150 });
  assert.deepEqual(small, { amount: 150, capped: true });
  assert.ok(small.amount <= 150, "a deposit may never exceed the job");
  // The rule on its own would have asked for 300 on a 150 job: the 3,963-on-a-3,620 mistake.
  assert.equal(ruleDeposit(120), 300);
});

test("deposit cap follows the exact total: a stored deposit above the job is capped to the cent", () => {
  const f = depositFigures({ depositAmount: 1800, contractTotal: 1619.98, amountPaid: 0, refundedAmount: 0 });
  assert.equal(f.asked, 1619.98);
  assert.equal(f.balance, 1619.98);
});

// ============================================================== quote-view ==

const COMPANY = "c0000000-0000-4000-8000-000000000001";
const JOB = "a0000000-0000-4000-8000-00000000000a";
const JOB_ID = "10000000-0000-4000-8000-000000000001";
const TOKEN = "b0000000-0000-4000-8000-00000000000b";

const SHARED = {
  "../_shared/quote-deposit.ts": quoteDeposit,
  "../_shared/job-push.ts": jobPush,
  "../_shared/push-recipients.ts": pushRecipients,
};

// The same real-function harness tests/accepted-price-functions.test.mjs uses:
// quote-view's TypeScript stripped by Node, its imports swapped for a fake
// Supabase client and the REAL shared deposit module. No network, no database.
function load(path, db) {
  let js = stripTypeScriptTypes(readFileSync(new URL(path, import.meta.url), "utf8"));
  const importRe = /^import\s*\{([\s\S]*?)\}\s*from\s*"([^"]+)";?[ \t]*$/gm;
  const provided = {};
  for (const [, list, from] of js.matchAll(importRe)) {
    const names = list.split(",").map((n) => n.trim()).filter(Boolean);
    if (/supabase-js/.test(from)) provided.createClient = () => db;
    else if (Object.hasOwn(SHARED, from)) {
      for (const n of names) { assert.ok(n in SHARED[from], `${from} exports no ${n}`); provided[n] = SHARED[from][n]; }
    } else assert.fail(`an import the harness does not supply: ${from}`);
  }
  js = js.replace(importRe, "").replace(/^export /gm, "");
  let handler = null;
  const Deno = { env: { get: () => undefined }, serve: (h) => { handler = h; } };
  const names = Object.keys(provided);
  new Function("Deno", "fetch", ...names, js)(Deno, async () => new Response("{}", { status: 404 }), ...names.map((n) => provided[n]));
  assert.equal(typeof handler, "function");
  return handler;
}

function fakeDb(tables) {
  const t = structuredClone(tables);
  class Query {
    constructor(table) { this.table = table; this.filters = []; this.cols = "*"; }
    select(cols) { this.cols = cols ?? "*"; return this; }
    eq(k, v) { this.filters.push((r) => String(r[k]) === String(v)); return this; }
    is(k, v) { this.filters.push((r) => (v === null ? r[k] == null : r[k] === v)); return this; }
    order() { return this; }
    limit() { return this; }
    update() { return this; }
    maybeSingle() { this.mode = "maybe"; return this.run(); }
    single() { this.mode = "one"; return this.run(); }
    then(ok, bad) { return this.run().then(ok, bad); }
    async run() {
      const rows = (t[this.table] ??= []).filter((r) => this.filters.every((f) => f(r)));
      const cols = String(this.cols).split(",").map((c) => c.trim()).filter(Boolean);
      const project = (r) => (cols.includes("*") ? r : Object.fromEntries(cols.filter((c) => c in r).map((c) => [c, r[c]])));
      const out = rows.map(project);
      if (this.mode === "maybe") return { data: out[0] ?? null, error: null };
      if (this.mode === "one") return { data: out[0] ?? null, error: out[0] ? null : { message: "no row" } };
      return { data: out, error: null };
    }
  }
  return { from: (table) => new Query(table), rpc: async () => ({ data: true, error: null }) };
}

function quoteWorld({ job = {}, lines = [] } = {}) {
  const db = fakeDb({
    jobs: [{
      id: JOB_ID, sync_id: JOB, company_id: COMPANY, customer_name: "Pat", address: "1 Oak St", phone: "",
      status: "SENT", deleted_at: null, quote_token: TOKEN, contract_total: 0, accepted_total: null, signed_at: null,
      quote_approved_at: null, quote_approved_name: "", reapproval_required_at: null, reapproval_reason: "",
      amount_paid: 0, refunded_amount: 0, deposit_amount: 0, tax_rate_percent: 0, discount_percent: 0,
      quote_viewed_at: "2026-09-20T12:00:00Z", calibration_pixels_per_foot: 20,
      quote_phone_attempts: 0, quote_phone_locked_until: null, ...job,
    }],
    companies: [{ id: COMPANY, name: "Test Fence Co", phone: "", email: "" }],
    estimate_line_items: lines.map((l) => ({ company_id: COMPANY, job_sync_id: JOB, deleted_at: null, taxable: false, ...l })),
    change_orders: [], fence_runs: [], payment_connections: [],
  });
  return { handler: load("../supabase/functions/quote-view/index.ts", db) };
}

const view = async (w) => {
  const res = await w.handler(new Request(`https://fn.test/quote-view?t=${TOKEN}`));
  return { status: res.status, body: await res.json() };
};

test("quote-view fallback: with nothing priced, the page adds the lines up EXACTLY, to the cent", async () => {
  const w = quoteWorld({ lines: [
    { description: "a", quantity: 1, unit_price: 1000, sort_order: 0 },
    { description: "b", quantity: 1, unit_price: 1269.32, sort_order: 1 },
  ] });
  const r = await view(w);
  assert.equal(r.status, 200, JSON.stringify(r.body));
  assert.equal(r.body.total, 2269.32);
  // PLANTED: the old fallback rounded up to the next ten.
  assert.equal(oldCeilTen(1000 + 1269.32), 2270);
  assert.notEqual(r.body.total, 2270);
});

test("quote-view fallback: tax is part of the exact sum", async () => {
  // 1000 taxable at 7% = 70 tax; 1070 exactly, where the old fallback said 1070 too -- so use a figure it would round.
  const w = quoteWorld({
    job: { tax_rate_percent: 7 },
    lines: [{ description: "a", quantity: 3, unit_price: 123.45, taxable: true, sort_order: 0 }],
  });
  const r = await view(w);
  // 3 * 123.45 = 370.35; tax 25.9245; total 396.2745 -> 396.27.
  assert.equal(r.body.total, 396.27);
  assert.equal(oldCeilTen(396.2745), 400);
});

test("quote-view: a stored total is shown as stored -- the fallback is the only thing rounded", async () => {
  const w = quoteWorld({ job: { contract_total: 2119.99 }, lines: [{ description: "a", quantity: 1, unit_price: 5, sort_order: 0 }] });
  const r = await view(w);
  assert.equal(r.body.total, 2119.99);
});

test("quote-view: the deposit is the one stored figure -- no extra hundred, no breakdown, no wording about it", async () => {
  // The owner's rule makes the deposit $1,800 for $1,630 of materials: ruleDeposit(1630) = 1800.
  const stored = ruleDeposit(1630);
  const w = quoteWorld({ job: { contract_total: 6200, deposit_amount: stored } });
  const r = await view(w);
  assert.equal(r.body.deposit, 1800);
  assert.equal(r.body.depositDue, 1800);
  // Nothing that would let a reader subtract an extra hundred back out.
  const text = JSON.stringify(r.body);
  assert.doesNotMatch(text, /transport|schedul|surcharge|handling|mobili[sz]ation|extra/i);
  assert.ok(!("depositExtra" in r.body) && !("depositBase" in r.body) && !("materials" in r.body));
});

test("quote-view never computes the deposit: it cannot add the extra hundred, only show what the contractor stored", () => {
  const src = code(read("supabase/functions/quote-view/index.ts"));
  for (const name of ["ruleDeposit", "suggestedDeposit", "DEPOSIT_PLUS", "DEPOSIT_ROUND_UP_TO"]) {
    assert.ok(!src.includes(name), `quote-view reaches for ${name}`);
  }
  // PLANTED: the same scan would see it if it did.
  assert.ok("import { ruleDeposit } from './x';".includes("ruleDeposit"));
});

// ===================================================== Kotlin parity guards ==

test("Kotlin carries the same deposit constants as TypeScript", () => {
  const kt = read("app/src/main/java/com/fenceestimator/app/estimate/JobMoney.kt");
  assert.equal(Number(/private const val DEPOSIT_ROUND_UP_TO = (\d+)L/.exec(kt)?.[1]), DEPOSIT_ROUND_UP_TO);
  assert.equal(Number(/private const val DEPOSIT_PLUS = (\d+)L/.exec(kt)?.[1]), DEPOSIT_PLUS);
});

test("the Kotlin test runs the same vector file this one does", () => {
  const kt = read("app/src/test/java/com/fenceestimator/app/estimate/JobMoneyDepositRuleTest.kt");
  assert.match(kt, /a29-deposit-rule-vectors\.json/);
});

test("Kotlin never seeds a deposit over one that is there, or into a job the customer is in", () => {
  // The old auto-fill overwrote a stored deposit: John Beaunissant's moved
  // from 9,910 to 5,730 ten seconds after he signed. The guards live in
  // JobMoney.depositToSeed and are tested in JobMoneyDepositRuleTest.kt; this
  // pins that they are still the first two lines of it.
  const kt = code(read("app/src/main/java/com/fenceestimator/app/estimate/JobMoney.kt"));
  const body = /fun depositToSeed\([^)]*\): Double\? \{([\s\S]*?)\n    \}/.exec(kt)?.[1] ?? "";
  assert.match(body, /if \(job\.depositAmount > 0\.005\) return null/);
  assert.match(body, /if \(customerIsInIt\(job\)\) return null/);
});
