package com.fenceestimator.app.estimate.parity

import com.fenceestimator.app.estimate.EstimateEngine
import kotlinx.serialization.decodeFromString
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test
import java.io.File

/**
 * Replays every committed fixture through the engine and demands the same
 * answer, stage by stage, with no tolerance.
 *
 * This is what fails the phone build when a formula moves without the
 * fixtures (and the server port) moving with it. It names the case and the
 * first stage that disagrees -- geometry before net feet before entries
 * before items before totals -- because a wrong total is a symptom and the
 * first wrong intermediate is the cause.
 */
class ParityFixtureCheck {

    private val fixtureDir: File by lazy {
        // Gradle runs unit tests with the module (app/) as the working
        // directory; from the repo root the same folder is one level up.
        listOf(File("fixtures/pricing"), File("../fixtures/pricing"))
            .firstOrNull { it.isDirectory }?.absoluteFile
            ?: throw AssertionError(
                "fixtures/pricing not found from ${File(".").absolutePath}; regenerate with " +
                    "FENCEFLOW_PARITY_OUT=\$(pwd)/fixtures/pricing ./gradlew testDebugUnitTest --tests \"*ParityFixtureWriter*\""
            )
    }

    private fun fixtureFiles(): List<File> =
        fixtureDir.listFiles { f -> f.isFile && f.name.endsWith(".json") && f.name != "manifest.json" }
            .orEmpty().sortedBy { it.name }

    @Test
    fun `manifest version is the engine version`() {
        val manifest = ParityJson.decodeFromString<ParityManifest>(File(fixtureDir, "manifest.json").readText())
        assertEquals(
            "fixtures were generated by another engine version; regenerate them",
            EstimateEngine.PRICING_ENGINE_VERSION, manifest.version
        )
        assertEquals("manifest case_count disagrees with the files on disk", fixtureFiles().size, manifest.caseCount)
    }

    @Test
    fun `every case has a fixture and every fixture has a case`() {
        val onDisk = fixtureFiles().map { it.name.removeSuffix(".json") }.toSet()
        val inCode = ParityCases.all().map { it.id }.toSet()
        assertEquals(
            "cases and fixtures differ (missing: ${inCode - onDisk}, stale: ${onDisk - inCode}); regenerate",
            inCode, onDisk
        )
    }

    @Test
    fun `every fixture replays exactly`() {
        val casesById = ParityCases.all().associateBy { it.id }
        val failures = mutableListOf<String>()

        fixtureFiles().forEach { file ->
            val fixture = ParityJson.decodeFromString<ParityFixture>(file.readText())
            if (fixture.engine.version != EstimateEngine.PRICING_ENGINE_VERSION) {
                failures += "${fixture.case}: fixture engine ${fixture.engine.version} != ${EstimateEngine.PRICING_ENGINE_VERSION}"
                return@forEach
            }
            val case = casesById[fixture.case]
            if (case != null && case.input != fixture.input) {
                failures += "${fixture.case}: the case's input changed since the fixture was written; regenerate"
                return@forEach
            }
            val actual = PricingRunner.price(fixture.input)
            val divergence = firstDivergence(fixture.expected, actual)
            if (divergence != null) failures += "${fixture.case}: first divergent stage = $divergence"
        }

        assertTrue(fixtureFiles().isNotEmpty())
        if (failures.isNotEmpty()) {
            fail(
                "${failures.size} of ${fixtureFiles().size} fixtures diverge from the engine. Either the engine changed " +
                    "(bump PRICING_ENGINE_VERSION, regenerate, and move the server port in the same commit) or " +
                    "the change is a bug.\n" + failures.joinToString("\n")
            )
        }
    }

    companion object {
        /**
         * The earliest stage at which two outputs disagree, or null when they
         * are identical. Exact equality throughout: a Double is the same Double
         * or it is a divergence.
         */
        fun firstDivergence(expected: PricingOutput, actual: PricingOutput): String? {
            if (expected.engineVersion != actual.engineVersion) {
                return "engine_version (${expected.engineVersion} vs ${actual.engineVersion})"
            }
            if (expected.runs.size != actual.runs.size) {
                return "runs (count ${expected.runs.size} vs ${actual.runs.size})"
            }
            expected.runs.zip(actual.runs).forEach { (e, a) ->
                val tag = "run ${e.runSyncId}"
                if (e.runSyncId != a.runSyncId) return "$tag identity (vs ${a.runSyncId})"
                if (e.isTeardown != a.isTeardown) return "$tag is_teardown"
                if (e.grossFeet != a.grossFeet || e.geometry != a.geometry) {
                    return "$tag geometry\n  expected gross ${e.grossFeet} ${e.geometry}\n  actual   gross ${a.grossFeet} ${a.geometry}"
                }
                if (e.gateCount != a.gateCount || e.gateFeet != a.gateFeet || e.netFeet != a.netFeet) {
                    return "$tag net_feet\n  expected gates ${e.gateCount} x ${e.gateFeet} ft -> ${e.netFeet}" +
                        "\n  actual   gates ${a.gateCount} x ${a.gateFeet} ft -> ${a.netFeet}"
                }
                if (e.posts != a.posts) return "$tag posts\n  expected ${e.posts}\n  actual   ${a.posts}"
                diffList("$tag entries", e.entries, a.entries)?.let { return it }
                diffList("$tag takeoff", e.takeoff, a.takeoff)?.let { return it }
            }
            diffList("items", expected.items, actual.items)?.let { return it }
            diffList("unmatched_roles", expected.unmatchedRoles, actual.unmatchedRoles)?.let { return it }
            diffList("zero_priced", expected.zeroPriced, actual.zeroPriced)?.let { return it }
            diffList("zero_priced_names", expected.zeroPricedNames, actual.zeroPricedNames)?.let { return it }
            if (expected.linearFeet != actual.linearFeet ||
                expected.teardownLinearFeet != actual.teardownLinearFeet ||
                expected.billableLinearFeet != actual.billableLinearFeet
            ) {
                return "feet\n  expected linear ${expected.linearFeet} teardown ${expected.teardownLinearFeet} billable ${expected.billableLinearFeet}" +
                    "\n  actual   linear ${actual.linearFeet} teardown ${actual.teardownLinearFeet} billable ${actual.billableLinearFeet}"
            }
            diffList("totals_items", expected.totalsItems, actual.totalsItems)?.let { return it }
            if (expected.totals != actual.totals) return "totals\n  expected ${expected.totals}\n  actual   ${actual.totals}"
            // Anything the stages above did not cover -- there should be nothing.
            if (expected != actual) return "output (a field no stage names; extend firstDivergence)"
            return null
        }

        private fun <T> diffList(stage: String, expected: List<T>, actual: List<T>): String? {
            if (expected.size != actual.size) {
                return "$stage (count ${expected.size} vs ${actual.size})\n  expected ${expected}\n  actual   ${actual}"
            }
            expected.zip(actual).forEachIndexed { i, (e, a) ->
                if (e != a) return "$stage[$i]\n  expected $e\n  actual   $a"
            }
            return null
        }
    }
}
