package com.fenceestimator.app.cloud

import com.fenceestimator.app.data.ChangeOrder
import com.fenceestimator.app.data.Employee
import com.fenceestimator.app.data.EstimateLineItem
import com.fenceestimator.app.data.Expense
import com.fenceestimator.app.data.ExpenseCategory
import com.fenceestimator.app.data.FenceRun
import com.fenceestimator.app.data.FenceType
import com.fenceestimator.app.data.JobStep
import com.fenceestimator.app.data.JobStepKind
import com.fenceestimator.app.data.Manufacturer
import com.fenceestimator.app.data.MaterialCategory
import com.fenceestimator.app.data.MaterialItem
import com.fenceestimator.app.data.MaterialRole
import com.fenceestimator.app.data.PricingTier
import com.fenceestimator.app.data.PunchListItem
import com.fenceestimator.app.data.Repository
import com.fenceestimator.app.data.SiteMarker
import com.fenceestimator.app.data.SiteMarkerKind
import com.fenceestimator.app.data.TimeEntry
import io.github.jan.supabase.postgrest.postgrest
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import java.time.Instant

/* ---------------- wire shapes ---------------- */

@Serializable
data class CloudEmployee(
    @SerialName("company_id") val companyId: String,
    @SerialName("sync_id") val syncId: String,
    val name: String = "",
    val role: String = "",
    val phone: String = "",
    val email: String = "",
    val notes: String = "",
    @SerialName("hourly_rate") val hourlyRate: Double = 0.0
)

@Serializable
data class CloudManufacturer(
    @SerialName("company_id") val companyId: String,
    @SerialName("sync_id") val syncId: String,
    val name: String = "",
    val email: String = "",
    val phone: String = "",
    val address: String = "",
    val hours: String = "",
    val notes: String = ""
)

@Serializable
data class CloudFenceRun(
    @SerialName("company_id") val companyId: String,
    @SerialName("sync_id") val syncId: String,
    @SerialName("job_sync_id") val jobSyncId: String,
    val label: String = "",
    @SerialName("fence_type") val fenceType: String = "VINYL",
    @SerialName("color_or_finish") val colorOrFinish: String = "",
    @SerialName("points_encoded") val pointsEncoded: String = "",
    @SerialName("gates_encoded") val gatesEncoded: String = "",
    @SerialName("closed_loop") val closedLoop: Boolean = false,
    @SerialName("panel_width_ft") val panelWidthFt: Float = 6f,
    @SerialName("panel_height_ft") val panelHeightFt: Float = 6f,
    @SerialName("post_spacing_ft") val postSpacingFt: Float = 6f,
    @SerialName("concrete_bags_per_post") val concreteBagsPerPost: Float = 1f,
    @SerialName("manual_linear_feet") val manualLinearFeet: Float? = null,
    @SerialName("manual_corner_count") val manualCornerCount: Int = 0,
    @SerialName("suppressed_roles") val suppressedRolesCsv: String = ""
)

@Serializable
data class CloudLineItem(
    @SerialName("company_id") val companyId: String,
    @SerialName("sync_id") val syncId: String,
    @SerialName("job_sync_id") val jobSyncId: String,
    /**
     * Which fence run this line belongs to. Without it every line item pulled
     * from the cloud landed under "Other Items" as an orphan, sitting alongside
     * the real ones -- which is where the stray items nobody could explain came
     * from.
     */
    @SerialName("fence_run_sync_id") val fenceRunSyncId: String? = null,
    @SerialName("sort_order") val sortOrder: Int = 0,
    val description: String = "",
    val quantity: Double = 0.0,
    val unit: String = "EA",
    @SerialName("unit_price") val unitPrice: Double = 0.0,
    val taxable: Boolean = true,
    val role: String? = null,
    @SerialName("auto_generated") val autoGenerated: Boolean = false
)

@Serializable
data class CloudExpense(
    @SerialName("company_id") val companyId: String,
    @SerialName("sync_id") val syncId: String,
    @SerialName("job_sync_id") val jobSyncId: String,
    val category: String = "OTHER",
    val description: String = "",
    val amount: Double = 0.0
)

@Serializable
data class CloudPunchItem(
    @SerialName("company_id") val companyId: String,
    @SerialName("sync_id") val syncId: String,
    @SerialName("job_sync_id") val jobSyncId: String,
    val description: String = "",
    val resolved: Boolean = false
)

@Serializable
data class CloudChangeOrder(
    @SerialName("company_id") val companyId: String,
    @SerialName("sync_id") val syncId: String,
    @SerialName("job_sync_id") val jobSyncId: String,
    val description: String = "",
    @SerialName("additional_feet") val additionalFeet: Double = 0.0,
    @SerialName("additional_cost") val additionalCost: Double = 0.0,
    @SerialName("material_cost") val materialCost: Double = 0.0,
    @SerialName("signed_at") val signedAt: String? = null
)

@Serializable
data class CloudJobStep(
    @SerialName("company_id") val companyId: String,
    @SerialName("sync_id") val syncId: String,
    @SerialName("job_sync_id") val jobSyncId: String,
    val kind: String = "INSTALL",
    val description: String = "",
    val checked: Boolean = false,
    @SerialName("verified_with_customer") val verifiedWithCustomer: Boolean = false,
    @SerialName("sort_order") val sortOrder: Int = 0
)

@Serializable
data class CloudSiteMarker(
    @SerialName("company_id") val companyId: String,
    @SerialName("sync_id") val syncId: String,
    @SerialName("job_sync_id") val jobSyncId: String,
    val kind: String = "OBSTACLE",
    val x: Float = 0f,
    val y: Float = 0f,
    val label: String = ""
)

@Serializable
data class CloudMaterialItem(
    @SerialName("company_id") val companyId: String,
    @SerialName("sync_id") val syncId: String,
    val name: String = "",
    val category: String = "MISC",
    val role: String = "NONE",
    @SerialName("fence_type") val fenceType: String = "UNIVERSAL",
    @SerialName("color_or_finish") val colorOrFinish: String = "",
    val unit: String = "EA",
    @SerialName("unit_price") val unitPrice: Double = 0.0,
    val taxable: Boolean = true,
    @SerialName("covers_ft") val coversFt: Float? = null,
    @SerialName("is_active") val isActive: Boolean = true,
    @SerialName("source_doc") val sourceDoc: String = ""
)

@Serializable
data class CloudPricingTier(
    @SerialName("company_id") val companyId: String,
    @SerialName("sync_id") val syncId: String,
    val name: String = "",
    @SerialName("labor_rate_per_ft") val laborRatePerFt: Double = 0.0,
    @SerialName("labor_flat_fee") val laborFlatFee: Double = 0.0,
    @SerialName("markup_percent") val markupPercent: Double = 0.0,
    @SerialName("discount_percent") val discountPercent: Double = 0.0,
    @SerialName("sort_order") val sortOrder: Int = 0
)

@Serializable
data class CloudTimeEntry(
    @SerialName("company_id") val companyId: String,
    @SerialName("sync_id") val syncId: String,
    @SerialName("job_sync_id") val jobSyncId: String,
    @SerialName("started_at") val startedAt: String,
    @SerialName("ended_at") val endedAt: String? = null,
    @SerialName("hourly_rate") val hourlyRate: Double = 0.0,
    val notes: String = ""
)

/**
 * Pushes the app's non-job records to the cloud so the office website can see
 * them. This is the piece that was missing -- a crew member added on a phone
 * existed only on that phone, which is exactly why they never showed up on the
 * website.
 *
 * Upserts on (company_id, sync_id), so running it repeatedly is safe and never
 * creates duplicates. Deliberately push-only for now: the phone stays the
 * source of truth for these while the web side is still read-mostly, which
 * avoids a half-built two-way merge quietly overwriting field data.
 */
object EntitySync {

    suspend fun pushAll(repository: Repository, companyId: String): Result<Int> =
        withContext(Dispatchers.IO) {
            runCatching {
                var pushed = 0
                pushed += pushEmployees(repository, companyId)
                pushed += pushManufacturers(repository, companyId)
                pushed += pushFenceRuns(repository, companyId)
                pushed += pushTimeEntries(repository, companyId)
                pushed += pushCatalog(repository, companyId)
                pushed += pushPricingTiers(repository, companyId)
                pushed += pushJobChildren(repository, companyId)
                pushed
            }
        }

    /**
     * Everything that hangs off a job: line items, expenses, punch list,
     * change orders, checklists and site markers.
     *
     * Collected in one pass over the jobs so the whole set is pushed with one
     * request per table, rather than one per job.
     */
    private suspend fun pushJobChildren(repository: Repository, companyId: String): Int {
        val jobs = repository.getAllJobs()
        if (jobs.isEmpty()) return 0

        val lineItems = mutableListOf<CloudLineItem>()
        val expenses = mutableListOf<CloudExpense>()
        val punch = mutableListOf<CloudPunchItem>()
        val orders = mutableListOf<CloudChangeOrder>()
        val steps = mutableListOf<CloudJobStep>()
        val markers = mutableListOf<CloudSiteMarker>()

        jobs.forEach { job ->
            val js = job.syncId
            val runSyncIdById = repository.getFenceRuns(job.id).associate { it.id to it.syncId }
            repository.getLineItems(job.id).forEach {
                lineItems += CloudLineItem(
                    companyId, it.syncId, js, it.fenceRunId?.let { id -> runSyncIdById[id] },
                    it.sortOrder, it.description, it.quantity,
                    it.unit, it.unitPrice, it.taxable, it.role?.name, it.isAutoGenerated
                )
            }
            repository.getExpenses(job.id).forEach {
                expenses += CloudExpense(companyId, it.syncId, js, it.category.name, it.description, it.amount)
            }
            repository.getPunchList(job.id).forEach {
                punch += CloudPunchItem(companyId, it.syncId, js, it.description, it.resolved)
            }
            repository.getChangeOrders(job.id).forEach {
                orders += CloudChangeOrder(
                    companyId, it.syncId, js, it.description, it.additionalFeet, it.additionalCost,
                    it.materialCost,
                    it.signedAt?.let { at -> Instant.ofEpochMilli(at).toString() }
                )
            }
            repository.getJobSteps(job.id).forEach {
                steps += CloudJobStep(
                    companyId, it.syncId, js, it.kind.name, it.description,
                    it.checked, it.verifiedWithCustomer, it.sortOrder
                )
            }
            repository.getSiteMarkers(job.id).forEach {
                markers += CloudSiteMarker(companyId, it.syncId, js, it.kind.name, it.x, it.y, it.label)
            }
        }

        var pushed = 0
        pushed += upsert("estimate_line_items", lineItems)
        pushed += upsert("expenses", expenses)
        pushed += upsert("punch_list_items", punch)
        pushed += upsert("change_orders", orders)
        pushed += upsert("job_steps", steps)
        pushed += upsert("site_markers", markers)
        return pushed
    }

    private suspend fun pushCatalog(repository: Repository, companyId: String): Int {
        val rows = repository.getAllMaterialItems().map {
            CloudMaterialItem(
                companyId, it.syncId, it.name, it.category.name, it.role.name,
                it.fenceType.name, it.colorOrFinish, it.unit, it.unitPrice,
                it.taxable, it.coversFt, it.isActive, it.sourceDoc
            )
        }
        return upsert("material_items", rows)
    }

    private suspend fun pushPricingTiers(repository: Repository, companyId: String): Int {
        val rows = repository.getAllPricingTiers().map {
            CloudPricingTier(
                companyId, it.syncId, it.name, it.laborRatePerFt,
                it.laborFlatFee, it.markupPercent, it.discountPercent, it.sortOrder
            )
        }
        return upsert("pricing_tiers", rows)
    }

    /** Chunked so a large catalog doesn't become one oversized request. */
    private suspend inline fun <reified T : Any> upsert(table: String, rows: List<T>): Int {
        if (rows.isEmpty()) return 0
        rows.chunked(200).forEach { chunk ->
            SupabaseModule.client.postgrest.from(table)
                .upsert(chunk) { onConflict = "company_id,sync_id" }
        }
        return rows.size
    }

    /**
     * Brings down anything this device doesn't have yet -- the path that makes
     * "new phone, sign in, everything's there" actually work.
     *
     * Matched on syncId, so a record already present is left alone rather than
     * duplicated. Existing local rows are not overwritten: the phone that has
     * been working offline keeps its own version until a proper two-way merge
     * exists for these tables.
     */
    suspend fun pullAll(repository: Repository, companyId: String): Result<Int> =
        withContext(Dispatchers.IO) {
            runCatching {
                var pulled = 0
                pulled += pullEmployees(repository, companyId)
                pulled += pullManufacturers(repository, companyId)
                pulled += pullPricingTiers(repository, companyId)
                pulled += pullCatalog(repository, companyId)
                pulled += pullFenceRuns(repository, companyId)
                pulled += pullJobChildren(repository, companyId)
                pulled
            }
        }

    private suspend fun pullPricingTiers(repository: Repository, companyId: String): Int {
        val cloud = SupabaseModule.client.postgrest.from("pricing_tiers")
            .select { filter { eq("company_id", companyId) } }
            .decodeList<CloudPricingTier>()
        // Match on NAME as well as sync id.
        //
        // Every install seeds its own copy of the standard tiers, each with its
        // own random sync id. Two phones therefore push six rows for the same
        // three tiers, then each pulls the other's three back -- so the list
        // doubles, and a third device triples it. That is the "everything shows
        // three times" bug. A tier is identified by its name, not by whichever
        // random id the phone that happened to create it invented.
        val existing = repository.getAllPricingTiers()
        val knownIds = existing.map { it.syncId }.toSet()
        val knownNames = existing.map { it.name.trim().lowercase() }.toSet()
        var added = 0
        cloud.filter { it.syncId !in knownIds && it.name.trim().lowercase() !in knownNames }.forEach { row ->
            repository.savePricingTier(
                PricingTier(
                    syncId = row.syncId, name = row.name,
                    laborRatePerFt = row.laborRatePerFt, laborFlatFee = row.laborFlatFee,
                    markupPercent = row.markupPercent, discountPercent = row.discountPercent,
                    sortOrder = row.sortOrder
                )
            )
            added++
        }
        return added
    }

    private suspend fun pullCatalog(repository: Repository, companyId: String): Int {
        val cloud = SupabaseModule.client.postgrest.from("material_items")
            .select { filter { eq("company_id", companyId) } }
            .decodeList<CloudMaterialItem>()
        // Same seeded-identity problem as pricing tiers: a catalog item is the
        // same item if its name, role, fence type and colour match, whatever
        // sync id the phone that seeded it happened to generate.
        val existingItems = repository.getAllMaterialItems()
        val knownIds = existingItems.map { it.syncId }.toSet()
        fun identity(name: String, role: String, fenceType: String, colour: String) =
            listOf(name, role, fenceType, colour).joinToString("|") { it.trim().lowercase() }
        val knownIdentities = existingItems
            .map { identity(it.name, it.role.name, it.fenceType.name, it.colorOrFinish) }
            .toSet()
        var added = 0
        cloud.filter {
            it.syncId !in knownIds &&
                identity(it.name, it.role, it.fenceType, it.colorOrFinish) !in knownIdentities
        }.forEach { row ->
            repository.saveMaterialItem(
                MaterialItem(
                    syncId = row.syncId,
                    name = row.name,
                    category = runCatching { MaterialCategory.valueOf(row.category) }
                        .getOrDefault(MaterialCategory.MISC),
                    role = runCatching { MaterialRole.valueOf(row.role) }
                        .getOrDefault(MaterialRole.NONE),
                    fenceType = runCatching { FenceType.valueOf(row.fenceType) }
                        .getOrDefault(FenceType.UNIVERSAL),
                    colorOrFinish = row.colorOrFinish,
                    unit = row.unit,
                    unitPrice = row.unitPrice,
                    taxable = row.taxable,
                    coversFt = row.coversFt,
                    isActive = row.isActive,
                    sourceDoc = row.sourceDoc
                )
            )
            added++
        }
        return added
    }

    /**
     * Restores the records that hang off a job. A child whose job isn't on this
     * device yet is skipped rather than orphaned -- the next pass picks it up
     * once the job itself has come down.
     */
    private suspend fun pullJobChildren(repository: Repository, companyId: String): Int {
        val jobIdBySyncId = repository.getAllJobs().associateBy({ it.syncId }, { it.id })
        if (jobIdBySyncId.isEmpty()) return 0
        var added = 0

        // Clears out orphans left by the old pull, which dropped every line item
        // into "Other Items" because it discarded the run. Only auto-generated,
        // role-bearing lines are removed -- anything typed by hand has no role
        // and is left exactly where it is.
        repository.deleteOrphanedGeneratedLineItems()

        val lineItems = SupabaseModule.client.postgrest.from("estimate_line_items")
            .select { filter { eq("company_id", companyId) } }
            .decodeList<CloudLineItem>()
        val runIdBySyncId = jobIdBySyncId.values
            .flatMap { repository.getFenceRuns(it) }.associate { it.syncId to it.id }
        val knownItems = jobIdBySyncId.values
            .flatMap { repository.getLineItems(it) }.map { it.syncId }.toSet()

        // Refuse legacy orphans outright rather than pulling them and cleaning
        // up afterwards. A row with a real material role but no run was pushed
        // before line items carried their run; re-inserting it just recreates
        // the stray item, and the cleanup and the pull chase each other forever.
        // Hand-typed extras have role NONE or none at all, and still come down.
        val (legacyOrphans, usable) = lineItems.partition { row ->
            row.fenceRunSyncId == null && row.role != null && row.role != "NONE"
        }
        legacyOrphans.forEach { row ->
            repository.queueDeletion(row.syncId, "estimate_line_items")
        }

        usable.filter { it.syncId !in knownItems }.forEach { row ->
            val jobId = jobIdBySyncId[row.jobSyncId] ?: return@forEach
            repository.saveLineItem(
                EstimateLineItem(
                    syncId = row.syncId, jobId = jobId,
                    fenceRunId = row.fenceRunSyncId?.let { runIdBySyncId[it] },
                    sortOrder = row.sortOrder, description = row.description,
                    quantity = row.quantity, unit = row.unit, unitPrice = row.unitPrice,
                    taxable = row.taxable,
                    role = row.role?.let { r -> runCatching { MaterialRole.valueOf(r) }.getOrNull() } ?: MaterialRole.NONE,
                    isAutoGenerated = row.autoGenerated
                )
            )
            added++
        }

        val expenses = SupabaseModule.client.postgrest.from("expenses")
            .select { filter { eq("company_id", companyId) } }
            .decodeList<CloudExpense>()
        val knownExpenses = jobIdBySyncId.values
            .flatMap { repository.getExpenses(it) }.map { it.syncId }.toSet()
        expenses.filter { it.syncId !in knownExpenses }.forEach { row ->
            val jobId = jobIdBySyncId[row.jobSyncId] ?: return@forEach
            repository.saveExpense(
                Expense(
                    syncId = row.syncId, jobId = jobId,
                    category = runCatching { ExpenseCategory.valueOf(row.category) }
                        .getOrDefault(ExpenseCategory.OTHER),
                    description = row.description, amount = row.amount
                )
            )
            added++
        }

        val punch = SupabaseModule.client.postgrest.from("punch_list_items")
            .select { filter { eq("company_id", companyId) } }
            .decodeList<CloudPunchItem>()
        val knownPunch = jobIdBySyncId.values
            .flatMap { repository.getPunchList(it) }.map { it.syncId }.toSet()
        punch.filter { it.syncId !in knownPunch }.forEach { row ->
            val jobId = jobIdBySyncId[row.jobSyncId] ?: return@forEach
            repository.addPunchListItem(
                PunchListItem(
                    syncId = row.syncId, jobId = jobId,
                    description = row.description, resolved = row.resolved
                )
            )
            added++
        }

        // These four were pushed but never pulled back, so switching phones lost
        // signed change orders and clocked hours -- money and payroll records --
        // along with job checklists and site markers.

        val orders = SupabaseModule.client.postgrest.from("change_orders")
            .select { filter { eq("company_id", companyId) } }
            .decodeList<CloudChangeOrder>()
        val knownOrders = jobIdBySyncId.values
            .flatMap { repository.getChangeOrders(it) }.map { it.syncId }.toSet()
        orders.filter { it.syncId !in knownOrders }.forEach { row ->
            val jobId = jobIdBySyncId[row.jobSyncId] ?: return@forEach
            repository.saveChangeOrder(
                ChangeOrder(
                    syncId = row.syncId, jobId = jobId,
                    description = row.description,
                    additionalFeet = row.additionalFeet,
                    additionalCost = row.additionalCost,
                    materialCost = row.materialCost,
                    // The signature image itself is a local file that isn't
                    // synced yet, so only the fact and date of signing survive.
                    signedAt = row.signedAt?.let { at ->
                        CloudTime.parseMillis(at)
                    }
                )
            )
            added++
        }

        val times = SupabaseModule.client.postgrest.from("time_entries")
            .select { filter { eq("company_id", companyId) } }
            .decodeList<CloudTimeEntry>()
        val knownTimes = jobIdBySyncId.values
            .flatMap { repository.getTimeEntries(it) }.map { it.syncId }.toSet()
        times.filter { it.syncId !in knownTimes }.forEach { row ->
            val jobId = jobIdBySyncId[row.jobSyncId] ?: return@forEach
            val startedAt = CloudTime.parseMillis(row.startedAt)
                ?: return@forEach
            repository.insertTimeEntry(
                TimeEntry(
                    syncId = row.syncId, jobId = jobId,
                    startedAt = startedAt,
                    endedAt = row.endedAt?.let { at ->
                        CloudTime.parseMillis(at)
                    },
                    hourlyRate = row.hourlyRate, notes = row.notes
                )
            )
            added++
        }

        val steps = SupabaseModule.client.postgrest.from("job_steps")
            .select { filter { eq("company_id", companyId) } }
            .decodeList<CloudJobStep>()
        val knownSteps = jobIdBySyncId.values
            .flatMap { repository.getJobSteps(it) }.map { it.syncId }.toSet()
        steps.filter { it.syncId !in knownSteps }.forEach { row ->
            val jobId = jobIdBySyncId[row.jobSyncId] ?: return@forEach
            repository.insertJobStep(
                JobStep(
                    syncId = row.syncId, jobId = jobId,
                    kind = runCatching { JobStepKind.valueOf(row.kind) }
                        .getOrDefault(JobStepKind.INSTALL),
                    description = row.description, checked = row.checked,
                    verifiedWithCustomer = row.verifiedWithCustomer,
                    sortOrder = row.sortOrder
                )
            )
            added++
        }

        val markers = SupabaseModule.client.postgrest.from("site_markers")
            .select { filter { eq("company_id", companyId) } }
            .decodeList<CloudSiteMarker>()
        val knownMarkers = jobIdBySyncId.values
            .flatMap { repository.getSiteMarkers(it) }.map { it.syncId }.toSet()
        markers.filter { it.syncId !in knownMarkers }.forEach { row ->
            val jobId = jobIdBySyncId[row.jobSyncId] ?: return@forEach
            repository.addSiteMarker(
                SiteMarker(
                    syncId = row.syncId, jobId = jobId,
                    kind = runCatching { SiteMarkerKind.valueOf(row.kind) }
                        .getOrDefault(SiteMarkerKind.OBSTACLE),
                    x = row.x, y = row.y, label = row.label
                )
            )
            added++
        }

        return added
    }

    private suspend fun pullEmployees(repository: Repository, companyId: String): Int {
        val cloud = SupabaseModule.client.postgrest.from("employees")
            .select { filter { eq("company_id", companyId) } }
            .decodeList<CloudEmployee>()
        val known = repository.getAllEmployees().map { it.syncId }.toSet()
        var added = 0
        cloud.filter { it.syncId !in known }.forEach { row ->
            repository.saveEmployee(
                Employee(
                    syncId = row.syncId, name = row.name, role = row.role,
                    phone = row.phone, email = row.email, notes = row.notes,
                    hourlyRate = row.hourlyRate
                )
            )
            added++
        }
        return added
    }

    private suspend fun pullManufacturers(repository: Repository, companyId: String): Int {
        val cloud = SupabaseModule.client.postgrest.from("manufacturers")
            .select { filter { eq("company_id", companyId) } }
            .decodeList<CloudManufacturer>()
        val known = repository.getAllManufacturers().map { it.syncId }.toSet()
        var added = 0
        cloud.filter { it.syncId !in known }.forEach { row ->
            repository.saveManufacturer(
                Manufacturer(
                    syncId = row.syncId, name = row.name, email = row.email,
                    phone = row.phone, address = row.address, hours = row.hours, notes = row.notes
                )
            )
            added++
        }
        return added
    }

    private suspend fun pullFenceRuns(repository: Repository, companyId: String): Int {
        val cloud = SupabaseModule.client.postgrest.from("fence_runs")
            .select { filter { eq("company_id", companyId) } }
            .decodeList<CloudFenceRun>()

        // Runs belong to a job, so a run whose job hasn't synced down yet is
        // skipped rather than orphaned; the next pass picks it up.
        val jobIdBySyncId = repository.getAllJobs().associateBy({ it.syncId }, { it.id })
        val known = jobIdBySyncId.values.flatMap { repository.getFenceRuns(it) }.map { it.syncId }.toSet()

        var added = 0
        cloud.filter { it.syncId !in known }.forEach { row ->
            val localJobId = jobIdBySyncId[row.jobSyncId] ?: return@forEach
            repository.createFenceRun(
                FenceRun(
                    syncId = row.syncId,
                    jobId = localJobId,
                    label = row.label,
                    fenceType = runCatching { FenceType.valueOf(row.fenceType) }.getOrDefault(FenceType.VINYL),
                    colorOrFinish = row.colorOrFinish,
                    pointsEncoded = row.pointsEncoded,
                    gatesEncoded = row.gatesEncoded,
                    closedLoop = row.closedLoop,
                    panelWidthFt = row.panelWidthFt,
                    panelHeightFt = row.panelHeightFt,
                    postSpacingFt = row.postSpacingFt,
                    concreteBagsPerPost = row.concreteBagsPerPost,
                    manualLinearFeet = row.manualLinearFeet,
                    manualCornerCount = row.manualCornerCount,
                    suppressedRolesCsv = row.suppressedRolesCsv
                )
            )
            added++
        }
        return added
    }

    private suspend fun pushEmployees(repository: Repository, companyId: String): Int {
        val rows = repository.getAllEmployees().map { it.toCloud(companyId) }
        if (rows.isEmpty()) return 0
        SupabaseModule.client.postgrest.from("employees")
            .upsert(rows) { onConflict = "company_id,sync_id" }
        return rows.size
    }

    private suspend fun pushManufacturers(repository: Repository, companyId: String): Int {
        val rows = repository.getAllManufacturers().map { it.toCloud(companyId) }
        if (rows.isEmpty()) return 0
        SupabaseModule.client.postgrest.from("manufacturers")
            .upsert(rows) { onConflict = "company_id,sync_id" }
        return rows.size
    }

    private suspend fun pushFenceRuns(repository: Repository, companyId: String): Int {
        val jobs = repository.getAllJobs()
        val rows = jobs.flatMap { job ->
            repository.getFenceRuns(job.id).map { it.toCloud(companyId, job.syncId) }
        }
        if (rows.isEmpty()) return 0
        SupabaseModule.client.postgrest.from("fence_runs")
            .upsert(rows) { onConflict = "company_id,sync_id" }
        return rows.size
    }

    private suspend fun pushTimeEntries(repository: Repository, companyId: String): Int {
        val jobsBySyncId = repository.getAllJobs().associateBy({ it.id }, { it.syncId })
        // Only completed shifts: a running timer has no end yet and would land
        // in the cloud looking like a zero-length entry.
        val rows = repository.getAllTimeEntries()
            .filter { !it.isRunning }
            .mapNotNull { entry ->
                jobsBySyncId[entry.jobId]?.let { entry.toCloud(companyId, it) }
            }
        if (rows.isEmpty()) return 0
        SupabaseModule.client.postgrest.from("time_entries")
            .upsert(rows) { onConflict = "company_id,sync_id" }
        return rows.size
    }
}

/* ---------------- mapping ---------------- */

private fun Employee.toCloud(companyId: String) = CloudEmployee(
    companyId = companyId, syncId = syncId, name = name, role = role,
    phone = phone, email = email, notes = notes, hourlyRate = hourlyRate
)

private fun Manufacturer.toCloud(companyId: String) = CloudManufacturer(
    companyId = companyId, syncId = syncId, name = name, email = email,
    phone = phone, address = address, hours = hours, notes = notes
)

private fun FenceRun.toCloud(companyId: String, jobSyncId: String) = CloudFenceRun(
    companyId = companyId, syncId = syncId, jobSyncId = jobSyncId,
    label = label, fenceType = fenceType.name, colorOrFinish = colorOrFinish,
    pointsEncoded = pointsEncoded, gatesEncoded = gatesEncoded, closedLoop = closedLoop,
    panelWidthFt = panelWidthFt, panelHeightFt = panelHeightFt,
    postSpacingFt = postSpacingFt, concreteBagsPerPost = concreteBagsPerPost,
    manualLinearFeet = manualLinearFeet, manualCornerCount = manualCornerCount,
    suppressedRolesCsv = suppressedRolesCsv
)

private fun TimeEntry.toCloud(companyId: String, jobSyncId: String) = CloudTimeEntry(
    companyId = companyId, syncId = syncId, jobSyncId = jobSyncId,
    startedAt = Instant.ofEpochMilli(startedAt).toString(),
    endedAt = endedAt?.let { Instant.ofEpochMilli(it).toString() },
    hourlyRate = hourlyRate, notes = notes
)

/**
 * Removes local rows that another device deleted.
 *
 * The other half of the tombstone fix. [JobSync] handles jobs; every other
 * synced table went through a blanket upsert, which meant a device that still
 * held a local copy of a deleted line item or change order pushed it straight
 * back up. For money-bearing tables that is not just clutter -- resurrected
 * line items and change orders inflate the job total, which is why two devices
 * showed different figures for the same job.
 *
 * Runs before the push, so nothing deleted elsewhere is uploaded again on the
 * same pass.
 */
object DeletionReaper {

    @kotlinx.serialization.Serializable
    private data class TombstonedRow(@kotlinx.serialization.SerialName("sync_id") val syncId: String)

    suspend fun reap(repository: com.fenceestimator.app.data.Repository, companyId: String): Result<Int> =
        runCatching {
            var removed = 0
            com.fenceestimator.app.data.SyncTables.ALL.forEach { table ->
                val deletedIds = SupabaseModule.client.postgrest.from(table)
                    .select(io.github.jan.supabase.postgrest.query.Columns.list("sync_id")) {
                        filter {
                            eq("company_id", companyId)
                            // "not null" rather than a date window: a device that
                            // has been off for a month must still learn about
                            // everything deleted while it was away.
                            filterNot("deleted_at", io.github.jan.supabase.postgrest.query.filter.FilterOperator.IS, "null")
                        }
                    }
                    .decodeList<TombstonedRow>()
                    .map { it.syncId }

                if (deletedIds.isNotEmpty()) {
                    removed += repository.deleteLocalRowsBySyncId(table, deletedIds)
                }
            }
            removed
        }
}
