package com.fenceestimator.app.ui.estimate

import android.content.Context
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.fenceestimator.app.data.BusinessProfile
import com.fenceestimator.app.data.EstimateLineItem
import com.fenceestimator.app.data.FenceRun
import com.fenceestimator.app.data.Job
import com.fenceestimator.app.data.MaterialItem
import com.fenceestimator.app.data.Repository
import com.fenceestimator.app.estimate.EstimateEngine
import com.fenceestimator.app.estimate.PdfExporter
import com.fenceestimator.app.geometry.FenceCodec
import com.fenceestimator.app.geometry.FenceGeometryEngine
import com.fenceestimator.app.ui.survey.SurveyViewModel
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.SharedFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.io.File

class EstimateViewModel(private val repository: Repository, private val jobId: Long) : ViewModel() {
    val job: StateFlow<Job?> = repository.observeJob(jobId)
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), null)

    val runs: StateFlow<List<FenceRun>> = repository.observeFenceRuns(jobId)
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), emptyList())

    val lineItems: StateFlow<List<EstimateLineItem>> = repository.observeLineItems(jobId)
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), emptyList())

    val catalog: StateFlow<List<MaterialItem>> = repository.observeCatalog()
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), emptyList())

    private val _message = MutableSharedFlow<String>(extraBufferCapacity = 1)
    /** Surfaces why a generate attempt produced nothing, instead of failing silently. */
    val message: SharedFlow<String> = _message

    fun regenerateSuggested(run: FenceRun) {
        viewModelScope.launch {
            // Grid drawings have a known fixed scale, so there is no reason to
            // demand a calibration step first -- set it here and carry on rather
            // than refusing to generate anything.
            var pxPerFt = job.value?.calibrationPixelsPerFoot
            if (pxPerFt == null) {
                val current = job.value
                if (current != null && current.surveyImagePath == null) {
                    pxPerFt = SurveyViewModel.PIXELS_PER_FOOT_GRID
                    repository.updateJob(current.copy(calibrationPixelsPerFoot = pxPerFt))
                } else {
                    _message.tryEmit("Tap two points in Calibrate mode on the survey photo to set the scale first.")
                    return@launch
                }
            }
            val points = FenceCodec.decodePoints(run.pointsEncoded)
            if (points.size < 2) {
                _message.tryEmit("Draw the fence line for \"${run.label.ifBlank { "this run" }}\" on the Survey screen first.")
                return@launch
            }

            var availableCatalog = catalog.value
            if (availableCatalog.isEmpty()) {
                // Catalog can be empty on installs affected by the old seeding bug; repair and retry.
                repository.ensureSeedDataPresent()
                availableCatalog = repository.observeCatalog().first()
            }
            if (availableCatalog.isEmpty()) {
                _message.tryEmit("Your materials catalog is empty. Add items under Catalog, then try again.")
                return@launch
            }

            val suggestions = EstimateEngine.suggestQuantities(run, pxPerFt)
            val items = EstimateEngine.buildLineItems(
                jobId = jobId,
                fenceRunId = run.id,
                run = run,
                suggestions = suggestions,
                catalog = availableCatalog,
                preferredManufacturerId = job.value?.preferredManufacturerId
            )
            repository.replaceAutoGeneratedLineItemsForRun(run.id, items)

            if (items.isEmpty()) {
                _message.tryEmit(
                    "No catalog items matched ${run.fenceType.name.replace("_", " ").lowercase()}. " +
                        "Add items for that fence type in Catalog."
                )
            } else {
                val posts = suggestions.entries
                    .filter { it.role.name.endsWith("POST") }
                    .sumOf { it.quantity }
                _message.tryEmit("Generated ${items.size} line items (${posts.toInt()} posts).")
            }
        }
    }

    fun regenerateAll() {
        runs.value.forEach { regenerateSuggested(it) }
    }

    fun updateLineItem(item: EstimateLineItem) {
        viewModelScope.launch { repository.updateLineItem(item) }
    }

    fun deleteLineItem(item: EstimateLineItem) {
        viewModelScope.launch { repository.deleteLineItem(item) }
    }

    fun addManualLineItem() {
        viewModelScope.launch {
            repository.saveLineItem(
                EstimateLineItem(
                    jobId = jobId,
                    fenceRunId = null,
                    sortOrder = (lineItems.value.maxOfOrNull { it.sortOrder } ?: 0) + 1,
                    description = "New item",
                    quantity = 1.0,
                    unitPrice = 0.0,
                    isAutoGenerated = false
                )
            )
        }
    }

    fun linearFeetFor(run: FenceRun): Float {
        val pxPerFt = job.value?.calibrationPixelsPerFoot ?: return 0f
        val points = FenceCodec.decodePoints(run.pointsEncoded)
        return FenceGeometryEngine.analyze(points, pxPerFt, run.closedLoop).totalLinearFeet
    }

    fun totalLinearFeet(): Float = runs.value.sumOf { linearFeetFor(it).toDouble() }.toFloat()

    fun totals(): EstimateEngine.Totals {
        val currentJob = job.value ?: return EstimateEngine.Totals(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)
        return EstimateEngine.computeTotals(currentJob, lineItems.value, totalLinearFeet())
    }

    fun exportPdf(context: Context, business: BusinessProfile, isInvoice: Boolean = false, onReady: (File) -> Unit) {
        val currentJob = job.value ?: return
        viewModelScope.launch {
            val file = withContext(Dispatchers.IO) {
                PdfExporter.export(
                    context = context,
                    job = currentJob,
                    estimateNumber = jobId.toString().padStart(5, '0'),
                    business = business,
                    runs = runs.value,
                    lineItems = lineItems.value,
                    totals = totals(),
                    linearFeet = totalLinearFeet(),
                    isInvoice = isInvoice
                )
            }
            onReady(file)
        }
    }

    fun captureSignature(path: String) {
        val current = job.value ?: return
        viewModelScope.launch {
            repository.updateJob(current.copy(signatureImagePath = path, signedAt = System.currentTimeMillis()))
        }
    }
}
