package com.fenceestimator.app.data

import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.RawQuery
import androidx.room.Transaction
import androidx.room.Update
import kotlinx.coroutines.flow.Flow

@Dao
interface JobDao {
    @Query("SELECT * FROM jobs ORDER BY updatedAt DESC")
    fun observeAll(): Flow<List<Job>>

    @Query("SELECT * FROM jobs WHERE id = :jobId")
    fun observeById(jobId: Long): Flow<Job?>

    @Query("SELECT * FROM jobs WHERE id = :jobId")
    suspend fun getById(jobId: Long): Job?

    @Query("SELECT * FROM jobs WHERE scheduledDate >= :startMillis AND scheduledDate < :endMillis ORDER BY scheduledDate ASC")
    suspend fun getScheduledBetween(startMillis: Long, endMillis: Long): List<Job>

    @Query("SELECT * FROM jobs")
    suspend fun getAll(): List<Job>

    @Insert
    suspend fun insert(job: Job): Long

    @Update
    suspend fun update(job: Job)

    @Delete
    suspend fun delete(job: Job)
}

@Dao
interface FenceRunDao {
    @Query("SELECT * FROM fence_runs WHERE jobId = :jobId ORDER BY sortOrder ASC, syncId ASC")
    fun observeForJob(jobId: Long): Flow<List<FenceRun>>

    @Query("SELECT * FROM fence_runs WHERE jobId = :jobId ORDER BY sortOrder ASC, syncId ASC")
    suspend fun getForJob(jobId: Long): List<FenceRun>

    /** Every run in one query, for figures that span all jobs. */
    @Query("SELECT * FROM fence_runs ORDER BY sortOrder ASC, syncId ASC")
    suspend fun getAll(): List<FenceRun>

    @Query("SELECT * FROM fence_runs WHERE id = :id")
    suspend fun getById(id: Long): FenceRun?

    @Query("SELECT * FROM fence_runs WHERE id = :id")
    fun observeById(id: Long): Flow<FenceRun?>

    @Insert
    suspend fun insert(run: FenceRun): Long

    @Update
    suspend fun update(run: FenceRun)

    @Delete
    suspend fun delete(run: FenceRun)
}

@Dao
interface MaterialItemDao {
    // ORDER BY is load-bearing here, not cosmetic. Without it SQLite returns
    // rows in whatever order the storage engine likes, and the estimate
    // engine breaks ties by list position -- so the same drawing repriced
    // twice could pick a DIFFERENT product for the same role, and the
    // customer watched their quote flip between the white panel at $52.35
    // and the gray one at $54.50 "by itself".
    @Query("SELECT * FROM material_items ORDER BY category, name, id")
    suspend fun getAll(): List<MaterialItem>
    @Query("SELECT * FROM material_items WHERE isActive = 1 ORDER BY category, name")
    fun observeAllActive(): Flow<List<MaterialItem>>

    @Query("SELECT * FROM material_items ORDER BY category, name")
    fun observeAll(): Flow<List<MaterialItem>>

    @Query("SELECT * FROM material_items WHERE id = :id")
    suspend fun getById(id: Long): MaterialItem?

    @Query("SELECT * FROM material_items WHERE role = :role AND isActive = 1 ORDER BY coversFt ASC")
    suspend fun getByRole(role: MaterialRole): List<MaterialItem>

    @Query("SELECT COUNT(*) FROM material_items")
    suspend fun count(): Int

    /**
     * Removes catalog duplicates from the old double-seeding bug. Matches on
     * name+role+fenceType+colorOrFinish so genuinely different items (same
     * name, different manufacturer price) are left alone.
     */
    @Query(
        "DELETE FROM material_items WHERE id NOT IN (" +
            "SELECT MIN(id) FROM material_items " +
            "GROUP BY name, role, fenceType, colorOrFinish, IFNULL(manufacturerId, -1))"
    )
    suspend fun deleteDuplicates(): Int

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(item: MaterialItem): Long

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertAll(items: List<MaterialItem>)

    @Update
    suspend fun update(item: MaterialItem)

    @Delete
    suspend fun delete(item: MaterialItem)
}

@Dao
interface EstimateLineItemDao {
    @Query("SELECT * FROM estimate_line_items WHERE jobId = :jobId ORDER BY sortOrder ASC, syncId ASC")
    fun observeForJob(jobId: Long): Flow<List<EstimateLineItem>>

    @Query("SELECT * FROM estimate_line_items WHERE jobId = :jobId ORDER BY sortOrder ASC, syncId ASC")
    suspend fun getForJob(jobId: Long): List<EstimateLineItem>

    /** Every line item in one query, for figures that span all jobs. */
    @Query("SELECT * FROM estimate_line_items ORDER BY sortOrder ASC, syncId ASC")
    suspend fun getAll(): List<EstimateLineItem>

    @Insert
    suspend fun insert(item: EstimateLineItem): Long

    @Insert
    suspend fun insertAll(items: List<EstimateLineItem>)

    @Update
    suspend fun update(item: EstimateLineItem)

    @Delete
    suspend fun delete(item: EstimateLineItem)

    @Query("DELETE FROM estimate_line_items WHERE fenceRunId = :runId AND isAutoGenerated = 1")
    suspend fun deleteAutoGeneratedForRun(runId: Long)

    /**
     * Clears everything the takeoff produced for this run. Keyed on role rather
     * than the auto-generated flag because editing a line clears that flag --
     * so the old delete skipped edited lines and the next Suggest added a second
     * copy of each one. Hand-typed extras have no role and are left alone.
     */
    // role != 'NONE', not "role is not null". The column is not nullable -- it
    // stores the enum name and defaults to NONE -- so a null check matches every
    // row, which would take hand-typed extras with it if one were ever attached
    // to a run. NONE is what "no material role" actually looks like here.
    @Query("DELETE FROM estimate_line_items WHERE fenceRunId = :runId AND role != 'NONE'")
    suspend fun deleteGeneratedForRun(runId: Long)

    @Query("SELECT * FROM estimate_line_items WHERE fenceRunId = :runId AND role != 'NONE'")
    suspend fun getGeneratedForRun(runId: Long): List<EstimateLineItem>

    /**
     * Delete and re-insert as one unit. Two quick taps on Suggest Quantities
     * used to interleave -- both deletes ran, then both inserts -- which is the
     * other way the estimate ended up with everything twice.
     */
    @Transaction
    suspend fun replaceGeneratedForRun(runId: Long, items: List<EstimateLineItem>) {
        deleteGeneratedForRun(runId)
        insertAll(items)
    }

    @Query("DELETE FROM estimate_line_items WHERE jobId = :jobId")
    suspend fun deleteAllForJob(jobId: Long)

    /**
     * Takeoff lines that lost their fence run. Only the old cloud pull could
     * produce these.
     *
     * Matched on role != 'NONE', NOT on "role is not null". The column is not
     * nullable -- it stores the enum name and defaults to NONE -- so a null
     * check is always true and would delete the user's hand-typed extras along
     * with the orphans. A hand-typed item has no material role, which is what
     * NONE means, and that is what keeps it safe here.
     */
    @Query("DELETE FROM estimate_line_items WHERE fenceRunId IS NULL AND role != 'NONE'")
    suspend fun deleteOrphanedGenerated(): Int

    /** The orphans, so their cloud copies can be tombstoned before they are removed. */
    @Query("SELECT * FROM estimate_line_items WHERE fenceRunId IS NULL AND role != 'NONE'")
    suspend fun orphanedGenerated(): List<EstimateLineItem>
}

@Dao
interface ManufacturerDao {
    @Query("SELECT * FROM manufacturers ORDER BY name")
    fun observeAll(): Flow<List<Manufacturer>>

    @Query("SELECT * FROM manufacturers ORDER BY name")
    suspend fun getAll(): List<Manufacturer>

    @Query("SELECT * FROM manufacturers WHERE id = :id")
    suspend fun getById(id: Long): Manufacturer?

    @Insert
    suspend fun insert(manufacturer: Manufacturer): Long

    @Update
    suspend fun update(manufacturer: Manufacturer)

    @Delete
    suspend fun delete(manufacturer: Manufacturer)
}

@Dao
interface PricingTierDao {
    @Query("SELECT * FROM pricing_tiers")
    suspend fun getAll(): List<PricingTier>
    @Query("SELECT * FROM pricing_tiers ORDER BY sortOrder ASC, syncId ASC")
    fun observeAll(): Flow<List<PricingTier>>

    @Query("SELECT COUNT(*) FROM pricing_tiers")
    suspend fun count(): Int

    /** Removes duplicate tiers left behind by the old double-seeding bug, keeping the original of each name. */
    @Query("DELETE FROM pricing_tiers WHERE id NOT IN (SELECT MIN(id) FROM pricing_tiers GROUP BY name)")
    suspend fun deleteDuplicates(): Int

    @Insert
    suspend fun insert(tier: PricingTier): Long

    @Insert
    suspend fun insertAll(tiers: List<PricingTier>)

    @Update
    suspend fun update(tier: PricingTier)

    @Delete
    suspend fun delete(tier: PricingTier)
}

@Dao
interface JobPhotoDao {
    @Query("SELECT * FROM job_photos WHERE jobId = :jobId ORDER BY takenAt DESC")
    fun observeForJob(jobId: Long): Flow<List<JobPhoto>>

    @Query("SELECT * FROM job_photos WHERE jobId = :jobId")
    suspend fun getForJob(jobId: Long): List<JobPhoto>

    @Update
    suspend fun update(photo: JobPhoto)

    @Insert
    suspend fun insert(photo: JobPhoto): Long

    @Delete
    suspend fun delete(photo: JobPhoto)
}

@Dao
interface InventoryItemDao {
    @Query("SELECT * FROM inventory_items WHERE jobId = :jobId ORDER BY kind, sortOrder ASC, id ASC")
    fun observeForJob(jobId: Long): Flow<List<InventoryChecklistItem>>

    @Query("SELECT * FROM inventory_items WHERE jobId = :jobId")
    suspend fun getForJob(jobId: Long): List<InventoryChecklistItem>

    @Insert
    suspend fun insert(item: InventoryChecklistItem): Long

    @Insert
    suspend fun insertAll(items: List<InventoryChecklistItem>)

    @Update
    suspend fun update(item: InventoryChecklistItem)

    @Delete
    suspend fun delete(item: InventoryChecklistItem)

    @Query("DELETE FROM inventory_items WHERE jobId = :jobId AND kind = :kind")
    suspend fun deleteByKind(jobId: Long, kind: InventoryKind)
}

@Dao
interface PendingDeletionDao {
    @Query("SELECT * FROM pending_deletions")
    suspend fun getAll(): List<PendingDeletion>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(deletion: PendingDeletion)

    @Query("DELETE FROM pending_deletions WHERE syncId = :syncId")
    suspend fun clear(syncId: String)
}

@Dao
interface TimeEntryDao {
    @Query("SELECT * FROM time_entries WHERE jobId = :jobId ORDER BY startedAt DESC")
    fun observeForJob(jobId: Long): Flow<List<TimeEntry>>

    @Query("SELECT * FROM time_entries WHERE endedAt IS NULL ORDER BY startedAt DESC")
    fun observeRunning(): Flow<List<TimeEntry>>

    /** Finished shifts nobody has signed off yet, oldest first so the queue drains in order. */
    @Query(
        "SELECT * FROM time_entries WHERE endedAt IS NOT NULL " +
            "AND approvedAt IS NULL AND rejectedAt IS NULL ORDER BY endedAt ASC"
    )
    fun observeAwaitingApproval(): Flow<List<TimeEntry>>

    @Query("SELECT * FROM time_entries WHERE jobId = :jobId AND endedAt IS NULL LIMIT 1")
    suspend fun runningForJob(jobId: Long): TimeEntry?

    @Query("SELECT * FROM time_entries")
    suspend fun getAll(): List<TimeEntry>

    @Query("SELECT * FROM time_entries WHERE jobId = :jobId")
    suspend fun getForJob(jobId: Long): List<TimeEntry>

    @Insert
    suspend fun insert(entry: TimeEntry): Long

    @Update
    suspend fun update(entry: TimeEntry)

    @Delete
    suspend fun delete(entry: TimeEntry)
}

@Dao
interface SiteMarkerDao {
    @Query("SELECT * FROM site_markers WHERE jobId = :jobId")
    suspend fun getForJob(jobId: Long): List<SiteMarker>
    @Query("SELECT * FROM site_markers WHERE jobId = :jobId")
    fun observeForJob(jobId: Long): Flow<List<SiteMarker>>

    @Insert
    suspend fun insert(marker: SiteMarker): Long

    @Update
    suspend fun update(marker: SiteMarker)

    @Delete
    suspend fun delete(marker: SiteMarker)
}

@Dao
interface ChangeOrderDao {
    @Query("SELECT * FROM change_orders WHERE jobId = :jobId")
    suspend fun getForJob(jobId: Long): List<ChangeOrder>

    @Query("SELECT * FROM change_orders")
    suspend fun getAll(): List<ChangeOrder>
    @Query("SELECT * FROM change_orders WHERE jobId = :jobId ORDER BY createdAt DESC")
    fun observeForJob(jobId: Long): Flow<List<ChangeOrder>>

    @Insert
    suspend fun insert(order: ChangeOrder): Long

    @Update
    suspend fun update(order: ChangeOrder)

    @Delete
    suspend fun delete(order: ChangeOrder)
}

@Dao
interface JobStepDao {
    @Query("SELECT * FROM job_steps WHERE jobId = :jobId")
    suspend fun getForJob(jobId: Long): List<JobStep>
    @Query("SELECT * FROM job_steps WHERE jobId = :jobId ORDER BY kind, sortOrder")
    fun observeForJob(jobId: Long): Flow<List<JobStep>>

    @Query("SELECT COUNT(*) FROM job_steps WHERE jobId = :jobId")
    suspend fun countForJob(jobId: Long): Int

    @Insert
    suspend fun insertAll(steps: List<JobStep>)

    @Insert
    suspend fun insert(step: JobStep): Long

    @Update
    suspend fun update(step: JobStep)
}

@Dao
interface EmployeeDao {
    @Query("SELECT * FROM employees ORDER BY name")
    fun observeAll(): Flow<List<Employee>>

    @Query("SELECT * FROM employees ORDER BY name")
    suspend fun getAll(): List<Employee>

    @Query("SELECT * FROM employees WHERE id = :id")
    suspend fun getById(id: Long): Employee?

    @Insert
    suspend fun insert(employee: Employee): Long

    @Update
    suspend fun update(employee: Employee)

    @Delete
    suspend fun delete(employee: Employee)
}

@Dao
interface ExpenseDao {
    @Query("SELECT * FROM expenses WHERE jobId = :jobId ORDER BY date DESC")
    fun observeForJob(jobId: Long): Flow<List<Expense>>

    @Query("SELECT * FROM expenses WHERE jobId = :jobId ORDER BY date DESC")
    suspend fun getForJob(jobId: Long): List<Expense>

    @Query("SELECT * FROM expenses ORDER BY date DESC")
    suspend fun getAll(): List<Expense>

    @Insert
    suspend fun insert(expense: Expense): Long

    @Update
    suspend fun update(expense: Expense)

    @Delete
    suspend fun delete(expense: Expense)
}

@Dao
interface PunchListDao {
    @Query("SELECT * FROM punch_list_items WHERE jobId = :jobId")
    suspend fun getForJob(jobId: Long): List<PunchListItem>
    @Query("SELECT * FROM punch_list_items WHERE jobId = :jobId ORDER BY resolved ASC, createdAt DESC")
    fun observeForJob(jobId: Long): Flow<List<PunchListItem>>

    @Insert
    suspend fun insert(item: PunchListItem): Long

    @Update
    suspend fun update(item: PunchListItem)

    @Delete
    suspend fun delete(item: PunchListItem)
}

@Dao
interface FieldChangeDao {
    @Query("SELECT * FROM field_changes WHERE jobId = :jobId ORDER BY at DESC")
    fun observeForJob(jobId: Long): Flow<List<FieldChange>>

    /** Everything a manager hasn't looked at yet, newest first, across all jobs. */
    @Query("SELECT * FROM field_changes WHERE acknowledgedAt IS NULL ORDER BY at DESC")
    fun observeUnacknowledged(): Flow<List<FieldChange>>

    @Query("SELECT * FROM field_changes WHERE jobId = :jobId")
    suspend fun getForJob(jobId: Long): List<FieldChange>

    @Insert
    suspend fun insert(change: FieldChange): Long

    @Update
    suspend fun update(change: FieldChange)

    @Query("UPDATE field_changes SET acknowledgedAt = :at WHERE jobId = :jobId AND acknowledgedAt IS NULL")
    suspend fun acknowledgeAllForJob(jobId: Long, at: Long)
}

/**
 * Removes local rows that another device deleted.
 *
 * One raw-query DAO rather than thirteen near-identical `DELETE ... WHERE
 * syncId IN (...)` methods, because the difference between them is only the
 * table name and thirteen copies is thirteen chances to miss one when a table
 * is added.
 *
 * The table name is interpolated, which would be an injection risk if it came
 * from anywhere but a fixed list in [SyncTables]. It never does -- the values
 * are compile-time constants, and the sync ids are bound as parameters.
 */
@Dao
interface SyncMaintenanceDao {
    @RawQuery
    suspend fun execute(query: androidx.sqlite.db.SupportSQLiteQuery): Int
}

/** Every table that syncs, so the reaper and the pusher cannot drift apart. */
object SyncTables {
    /** Local Room table name to the cloud table it maps to; they match today. */
    val ALL: List<String> = listOf(
        "fence_runs", "estimate_line_items", "change_orders", "job_steps",
        "site_markers", "time_entries", "expenses", "punch_list_items",
        "employees", "manufacturers", "material_items", "pricing_tiers",
        "field_changes"
    )
}

@Dao
interface PaymentRecordDao {
    @Query("SELECT * FROM payment_records WHERE jobId = :jobId ORDER BY receivedAt DESC")
    fun observeForJob(jobId: Long): Flow<List<PaymentRecord>>

    @Query("SELECT * FROM payment_records ORDER BY receivedAt DESC")
    fun observeAll(): Flow<List<PaymentRecord>>

    @Query("SELECT * FROM payment_records")
    suspend fun getAll(): List<PaymentRecord>

    /** The money that actually moved inside a period -- what a report should count. */
    @Query("SELECT * FROM payment_records WHERE receivedAt BETWEEN :fromMillis AND :toMillis ORDER BY receivedAt DESC")
    suspend fun getBetween(fromMillis: Long, toMillis: Long): List<PaymentRecord>

    @Query("SELECT COALESCE(SUM(amount), 0) FROM payment_records WHERE jobId = :jobId")
    suspend fun netForJob(jobId: Long): Double

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(record: PaymentRecord): Long

    @Insert(onConflict = OnConflictStrategy.IGNORE)
    suspend fun insertAll(records: List<PaymentRecord>)

    @Query("SELECT * FROM payment_records WHERE syncId = :syncId LIMIT 1")
    suspend fun bySyncId(syncId: String): PaymentRecord?

    @Query("DELETE FROM payment_records WHERE syncId IN (:syncIds)")
    suspend fun deleteBySyncIds(syncIds: List<String>): Int
}
