package com.fenceestimator.app.data

import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Update
import kotlinx.coroutines.flow.Flow

@Dao
interface JobDao {
    @Query("SELECT * FROM jobs ORDER BY updatedAt DESC")
    fun observeAll(): Flow<List<Job>>

    @Query("SELECT * FROM jobs WHERE id = :jobId")
    fun observeById(jobId: Long): Flow<Job?>

    @Query("SELECT * FROM jobs WHERE id = :jobId")
    suspend fun getById(jobId: Long): Job?

    @Query("SELECT * FROM jobs WHERE scheduledDate >= :startMillis AND scheduledDate < :endMillis ORDER BY scheduledDate ASC")
    suspend fun getScheduledBetween(startMillis: Long, endMillis: Long): List<Job>

    @Query("SELECT * FROM jobs")
    suspend fun getAll(): List<Job>

    @Insert
    suspend fun insert(job: Job): Long

    @Update
    suspend fun update(job: Job)

    @Delete
    suspend fun delete(job: Job)
}

@Dao
interface FenceRunDao {
    @Query("SELECT * FROM fence_runs WHERE jobId = :jobId ORDER BY sortOrder ASC, id ASC")
    fun observeForJob(jobId: Long): Flow<List<FenceRun>>

    @Query("SELECT * FROM fence_runs WHERE jobId = :jobId ORDER BY sortOrder ASC, id ASC")
    suspend fun getForJob(jobId: Long): List<FenceRun>

    @Query("SELECT * FROM fence_runs WHERE id = :id")
    suspend fun getById(id: Long): FenceRun?

    @Query("SELECT * FROM fence_runs WHERE id = :id")
    fun observeById(id: Long): Flow<FenceRun?>

    @Insert
    suspend fun insert(run: FenceRun): Long

    @Update
    suspend fun update(run: FenceRun)

    @Delete
    suspend fun delete(run: FenceRun)
}

@Dao
interface MaterialItemDao {
    @Query("SELECT * FROM material_items")
    suspend fun getAll(): List<MaterialItem>
    @Query("SELECT * FROM material_items WHERE isActive = 1 ORDER BY category, name")
    fun observeAllActive(): Flow<List<MaterialItem>>

    @Query("SELECT * FROM material_items ORDER BY category, name")
    fun observeAll(): Flow<List<MaterialItem>>

    @Query("SELECT * FROM material_items WHERE id = :id")
    suspend fun getById(id: Long): MaterialItem?

    @Query("SELECT * FROM material_items WHERE role = :role AND isActive = 1 ORDER BY coversFt ASC")
    suspend fun getByRole(role: MaterialRole): List<MaterialItem>

    @Query("SELECT COUNT(*) FROM material_items")
    suspend fun count(): Int

    /**
     * Removes catalog duplicates from the old double-seeding bug. Matches on
     * name+role+fenceType+colorOrFinish so genuinely different items (same
     * name, different manufacturer price) are left alone.
     */
    @Query(
        "DELETE FROM material_items WHERE id NOT IN (" +
            "SELECT MIN(id) FROM material_items " +
            "GROUP BY name, role, fenceType, colorOrFinish, IFNULL(manufacturerId, -1))"
    )
    suspend fun deleteDuplicates(): Int

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(item: MaterialItem): Long

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertAll(items: List<MaterialItem>)

    @Update
    suspend fun update(item: MaterialItem)

    @Delete
    suspend fun delete(item: MaterialItem)
}

@Dao
interface EstimateLineItemDao {
    @Query("SELECT * FROM estimate_line_items WHERE jobId = :jobId ORDER BY sortOrder ASC, id ASC")
    fun observeForJob(jobId: Long): Flow<List<EstimateLineItem>>

    @Query("SELECT * FROM estimate_line_items WHERE jobId = :jobId ORDER BY sortOrder ASC, id ASC")
    suspend fun getForJob(jobId: Long): List<EstimateLineItem>

    @Insert
    suspend fun insert(item: EstimateLineItem): Long

    @Insert
    suspend fun insertAll(items: List<EstimateLineItem>)

    @Update
    suspend fun update(item: EstimateLineItem)

    @Delete
    suspend fun delete(item: EstimateLineItem)

    @Query("DELETE FROM estimate_line_items WHERE fenceRunId = :runId AND isAutoGenerated = 1")
    suspend fun deleteAutoGeneratedForRun(runId: Long)

    @Query("DELETE FROM estimate_line_items WHERE jobId = :jobId")
    suspend fun deleteAllForJob(jobId: Long)
}

@Dao
interface ManufacturerDao {
    @Query("SELECT * FROM manufacturers ORDER BY name")
    fun observeAll(): Flow<List<Manufacturer>>

    @Query("SELECT * FROM manufacturers ORDER BY name")
    suspend fun getAll(): List<Manufacturer>

    @Query("SELECT * FROM manufacturers WHERE id = :id")
    suspend fun getById(id: Long): Manufacturer?

    @Insert
    suspend fun insert(manufacturer: Manufacturer): Long

    @Update
    suspend fun update(manufacturer: Manufacturer)

    @Delete
    suspend fun delete(manufacturer: Manufacturer)
}

@Dao
interface PricingTierDao {
    @Query("SELECT * FROM pricing_tiers")
    suspend fun getAll(): List<PricingTier>
    @Query("SELECT * FROM pricing_tiers ORDER BY sortOrder ASC, id ASC")
    fun observeAll(): Flow<List<PricingTier>>

    @Query("SELECT COUNT(*) FROM pricing_tiers")
    suspend fun count(): Int

    /** Removes duplicate tiers left behind by the old double-seeding bug, keeping the original of each name. */
    @Query("DELETE FROM pricing_tiers WHERE id NOT IN (SELECT MIN(id) FROM pricing_tiers GROUP BY name)")
    suspend fun deleteDuplicates(): Int

    @Insert
    suspend fun insert(tier: PricingTier): Long

    @Insert
    suspend fun insertAll(tiers: List<PricingTier>)

    @Update
    suspend fun update(tier: PricingTier)

    @Delete
    suspend fun delete(tier: PricingTier)
}

@Dao
interface JobPhotoDao {
    @Query("SELECT * FROM job_photos WHERE jobId = :jobId ORDER BY takenAt DESC")
    fun observeForJob(jobId: Long): Flow<List<JobPhoto>>

    @Insert
    suspend fun insert(photo: JobPhoto): Long

    @Delete
    suspend fun delete(photo: JobPhoto)
}

@Dao
interface InventoryItemDao {
    @Query("SELECT * FROM inventory_items WHERE jobId = :jobId ORDER BY kind, sortOrder ASC, id ASC")
    fun observeForJob(jobId: Long): Flow<List<InventoryChecklistItem>>

    @Query("SELECT * FROM inventory_items WHERE jobId = :jobId")
    suspend fun getForJob(jobId: Long): List<InventoryChecklistItem>

    @Insert
    suspend fun insert(item: InventoryChecklistItem): Long

    @Insert
    suspend fun insertAll(items: List<InventoryChecklistItem>)

    @Update
    suspend fun update(item: InventoryChecklistItem)

    @Delete
    suspend fun delete(item: InventoryChecklistItem)

    @Query("DELETE FROM inventory_items WHERE jobId = :jobId AND kind = :kind")
    suspend fun deleteByKind(jobId: Long, kind: InventoryKind)
}

@Dao
interface TimeEntryDao {
    @Query("SELECT * FROM time_entries WHERE jobId = :jobId ORDER BY startedAt DESC")
    fun observeForJob(jobId: Long): Flow<List<TimeEntry>>

    @Query("SELECT * FROM time_entries WHERE endedAt IS NULL ORDER BY startedAt DESC")
    fun observeRunning(): Flow<List<TimeEntry>>

    @Query("SELECT * FROM time_entries WHERE jobId = :jobId AND endedAt IS NULL LIMIT 1")
    suspend fun runningForJob(jobId: Long): TimeEntry?

    @Query("SELECT * FROM time_entries")
    suspend fun getAll(): List<TimeEntry>

    @Query("SELECT * FROM time_entries WHERE jobId = :jobId")
    suspend fun getForJob(jobId: Long): List<TimeEntry>

    @Insert
    suspend fun insert(entry: TimeEntry): Long

    @Update
    suspend fun update(entry: TimeEntry)

    @Delete
    suspend fun delete(entry: TimeEntry)
}

@Dao
interface SiteMarkerDao {
    @Query("SELECT * FROM site_markers WHERE jobId = :jobId")
    suspend fun getForJob(jobId: Long): List<SiteMarker>
    @Query("SELECT * FROM site_markers WHERE jobId = :jobId")
    fun observeForJob(jobId: Long): Flow<List<SiteMarker>>

    @Insert
    suspend fun insert(marker: SiteMarker): Long

    @Delete
    suspend fun delete(marker: SiteMarker)
}

@Dao
interface ChangeOrderDao {
    @Query("SELECT * FROM change_orders WHERE jobId = :jobId")
    suspend fun getForJob(jobId: Long): List<ChangeOrder>
    @Query("SELECT * FROM change_orders WHERE jobId = :jobId ORDER BY createdAt DESC")
    fun observeForJob(jobId: Long): Flow<List<ChangeOrder>>

    @Insert
    suspend fun insert(order: ChangeOrder): Long

    @Update
    suspend fun update(order: ChangeOrder)

    @Delete
    suspend fun delete(order: ChangeOrder)
}

@Dao
interface JobStepDao {
    @Query("SELECT * FROM job_steps WHERE jobId = :jobId")
    suspend fun getForJob(jobId: Long): List<JobStep>
    @Query("SELECT * FROM job_steps WHERE jobId = :jobId ORDER BY kind, sortOrder")
    fun observeForJob(jobId: Long): Flow<List<JobStep>>

    @Query("SELECT COUNT(*) FROM job_steps WHERE jobId = :jobId")
    suspend fun countForJob(jobId: Long): Int

    @Insert
    suspend fun insertAll(steps: List<JobStep>)

    @Update
    suspend fun update(step: JobStep)
}

@Dao
interface EmployeeDao {
    @Query("SELECT * FROM employees ORDER BY name")
    fun observeAll(): Flow<List<Employee>>

    @Query("SELECT * FROM employees ORDER BY name")
    suspend fun getAll(): List<Employee>

    @Query("SELECT * FROM employees WHERE id = :id")
    suspend fun getById(id: Long): Employee?

    @Insert
    suspend fun insert(employee: Employee): Long

    @Update
    suspend fun update(employee: Employee)

    @Delete
    suspend fun delete(employee: Employee)
}

@Dao
interface ExpenseDao {
    @Query("SELECT * FROM expenses WHERE jobId = :jobId ORDER BY date DESC")
    fun observeForJob(jobId: Long): Flow<List<Expense>>

    @Query("SELECT * FROM expenses WHERE jobId = :jobId ORDER BY date DESC")
    suspend fun getForJob(jobId: Long): List<Expense>

    @Query("SELECT * FROM expenses ORDER BY date DESC")
    suspend fun getAll(): List<Expense>

    @Insert
    suspend fun insert(expense: Expense): Long

    @Update
    suspend fun update(expense: Expense)

    @Delete
    suspend fun delete(expense: Expense)
}

@Dao
interface PunchListDao {
    @Query("SELECT * FROM punch_list_items WHERE jobId = :jobId")
    suspend fun getForJob(jobId: Long): List<PunchListItem>
    @Query("SELECT * FROM punch_list_items WHERE jobId = :jobId ORDER BY resolved ASC, createdAt DESC")
    fun observeForJob(jobId: Long): Flow<List<PunchListItem>>

    @Insert
    suspend fun insert(item: PunchListItem): Long

    @Update
    suspend fun update(item: PunchListItem)

    @Delete
    suspend fun delete(item: PunchListItem)
}
