package com.fenceestimator.app.data

/**
 * Takeoff lines this phone has just written under a sync id the cloud may
 * already hold a tombstone for, and which therefore have to be brought back
 * to life there rather than reaped here.
 *
 * Why it exists: line sync ids are deterministic (run + role, see
 * EstimateEngine.deterministicSyncId), so a role that drops out of a takeoff
 * and later comes back is written again under the SAME id. If the tombstone
 * for the earlier removal had already reached the cloud, two things went
 * wrong on the next sync: DeletionReaper saw the id tombstoned and deleted
 * the brand-new local line, and the upsert that would have carried it up
 * rewrote the cloud row's content but left deleted_at set. About a second and
 * a half after Suggest Quantities the lines vanished and the price dropped
 * (live: 35 tombstoned role lines on live runs, 13 rewritten after their
 * tombstone -- Woody's LINE_POST and PANEL, $3,963.44 the cloud was hiding).
 *
 * With this, the reaper spares these ids ([reapable]) and the push sends
 * them, and only them, with an explicit `deleted_at: null` -- the same
 * resurrection price-job's commitLineItemWrite already does server-side --
 * then forgets them once the cloud has accepted it ([confirmPushed]).
 *
 * Only ids a regenerate on THIS phone just wrote, never "every live row":
 * the reaper runs before the push, but a pass whose reap failed (one bad
 * read) still pushes, and a blanket `deleted_at: null` would then undo every
 * delete another device had made since this phone last looked.
 *
 * Kept in Room ([PendingResurrection]), not in memory. The first version was
 * a list in memory, and the window it had to survive is exactly when a
 * process dies: a Suggest pressed at a job site with no signal, then the
 * phone left overnight. The reaper on reconnect found the list empty, took
 * the regenerated lines and any quantity typed on them since, and nothing
 * said so. [Repository.replaceAutoGeneratedLineItemsForRun] notes the ids in
 * the same transaction that writes the lines, and
 * [Repository.reapLineItems] reads them in the same transaction that deletes,
 * so the two can never interleave: a regenerate lands wholly before or wholly
 * after a reap. [Repository.clearAllLocalData] wipes the table with the rest.
 */
class LineItemResurrections(private val dao: PendingResurrectionDao) {

    /** A regenerate is writing these ids; the cloud may hold them tombstoned. Call inside the write's transaction. */
    suspend fun noteWritten(syncIds: Collection<String>) {
        if (syncIds.isEmpty()) return
        val now = System.currentTimeMillis()
        dao.insertAll(syncIds.distinct().map { PendingResurrection(syncId = it, queuedAt = now) })
    }

    /** These lines are gone from this phone again (tombstoned, deleted), so nothing to revive. */
    suspend fun forget(syncIds: Collection<String>) {
        // Chunked because SQLite caps bind variables per statement.
        syncIds.distinct().chunked(400).forEach { dao.deleteAll(it) }
    }

    /** The cloud accepted the resurrecting upsert for these ids. */
    suspend fun confirmPushed(syncIds: Collection<String>) = forget(syncIds)

    /** Every id still waiting to be revived. */
    suspend fun pending(): Set<String> = dao.allSyncIds().toSet()

    companion object {
        /**
         * Of [tombstoned] -- the ids the cloud says were deleted -- the ones
         * this phone may delete locally: everything except a line it has just
         * written again and not yet revived ([waiting]).
         */
        fun reapable(tombstoned: Collection<String>, waiting: Set<String>): List<String> =
            tombstoned.filterNot { it in waiting }
    }
}
