package com.fenceestimator.app.data

import kotlinx.coroutines.flow.Flow

class Repository(private val db: AppDatabase) {
    /** Flushes pending writes to disk so a raw copy of the DB file for backup is complete. */
    suspend fun checkpointForBackup() = db.checkpoint()

    private val jobDao = db.jobDao()
    private val fenceRunDao = db.fenceRunDao()
    private val materialDao = db.materialItemDao()
    private val lineItemDao = db.estimateLineItemDao()
    private val manufacturerDao = db.manufacturerDao()
    private val pricingTierDao = db.pricingTierDao()
    private val jobPhotoDao = db.jobPhotoDao()
    private val inventoryItemDao = db.inventoryItemDao()
    private val employeeDao = db.employeeDao()
    private val expenseDao = db.expenseDao()
    private val punchListDao = db.punchListDao()
    private val jobStepDao = db.jobStepDao()
    private val changeOrderDao = db.changeOrderDao()
    private val siteMarkerDao = db.siteMarkerDao()
    private val timeEntryDao = db.timeEntryDao()
    private val pendingDeletionDao = db.pendingDeletionDao()

    fun observeJobs(): Flow<List<Job>> = jobDao.observeAll()
    fun observeJob(id: Long): Flow<Job?> = jobDao.observeById(id)
    suspend fun getJob(id: Long): Job? = jobDao.getById(id)
    suspend fun getJobsScheduledBetween(startMillis: Long, endMillis: Long): List<Job> = jobDao.getScheduledBetween(startMillis, endMillis)
    suspend fun getAllJobs(): List<Job> = jobDao.getAll()
    suspend fun createJob(job: Job): Long = jobDao.insert(job)
    suspend fun updateJob(job: Job) = jobDao.update(job.copy(updatedAt = System.currentTimeMillis()))

    /**
     * Writes a job pulled from the cloud WITHOUT touching updatedAt -- the
     * cloud's timestamp has to survive, otherwise every download would look
     * locally-newer on the next pass and ping-pong back up forever.
     */
    suspend fun updateJobFromCloud(job: Job) = jobDao.update(job)

    suspend fun updateJobSyncStamp(jobId: Long, syncedAt: Long) {
        jobDao.getById(jobId)?.let { jobDao.update(it.copy(lastSyncedAt = syncedAt)) }
    }
    /**
     * Deletes locally and records that the cloud copy must go too.
     *
     * Deleting used to be local-only, so the row survived in Supabase and the
     * next sync pulled it straight back as "a job this phone is missing" --
     * which is why deleted jobs kept reappearing.
     */
    suspend fun deleteJob(job: Job) {
        jobDao.delete(job)
        pendingDeletionDao.insert(PendingDeletion(syncId = job.syncId, tableName = "jobs"))
    }

    suspend fun pendingDeletions(): List<PendingDeletion> = pendingDeletionDao.getAll()
    suspend fun clearPendingDeletion(syncId: String) = pendingDeletionDao.clear(syncId)

    suspend fun deleteEmployeeSynced(employee: Employee) {
        employeeDao.delete(employee)
        pendingDeletionDao.insert(PendingDeletion(syncId = employee.syncId, tableName = "employees"))
    }

    fun observeFenceRuns(jobId: Long): Flow<List<FenceRun>> = fenceRunDao.observeForJob(jobId)
    suspend fun getFenceRuns(jobId: Long): List<FenceRun> = fenceRunDao.getForJob(jobId)
    fun observeFenceRun(id: Long): Flow<FenceRun?> = fenceRunDao.observeById(id)
    suspend fun getFenceRun(id: Long): FenceRun? = fenceRunDao.getById(id)
    suspend fun createFenceRun(run: FenceRun): Long = fenceRunDao.insert(run)
    suspend fun updateFenceRun(run: FenceRun) = fenceRunDao.update(run)
    suspend fun deleteFenceRun(run: FenceRun) = fenceRunDao.delete(run)

    fun observeCatalog(): Flow<List<MaterialItem>> = materialDao.observeAllActive()
    fun observeFullCatalog(): Flow<List<MaterialItem>> = materialDao.observeAll()
    suspend fun getByRole(role: MaterialRole): List<MaterialItem> = materialDao.getByRole(role)
    suspend fun saveMaterialItem(item: MaterialItem): Long =
        materialDao.insert(item.copy(lastUpdated = System.currentTimeMillis()))
    suspend fun updateMaterialItem(item: MaterialItem) =
        materialDao.update(item.copy(lastUpdated = System.currentTimeMillis()))
    suspend fun deleteMaterialItem(item: MaterialItem) = materialDao.delete(item)
    suspend fun addMaterialItems(items: List<MaterialItem>) = materialDao.insertAll(items)

    fun observeLineItems(jobId: Long): Flow<List<EstimateLineItem>> = lineItemDao.observeForJob(jobId)
    suspend fun getLineItems(jobId: Long): List<EstimateLineItem> = lineItemDao.getForJob(jobId)
    /**
     * Swaps this run's takeoff for a freshly generated one.
     *
     * Anything dropped is tombstoned so the cloud copy goes too. Without that,
     * a delete was local-only: the old rows stayed in the cloud, and the very
     * next sync pulled them back down beside the new ones. That is why pressing
     * Suggest Quantities twice still ended up with everything listed twice even
     * after the local duplicate was fixed.
     */
    suspend fun replaceAutoGeneratedLineItemsForRun(runId: Long, items: List<EstimateLineItem>) {
        val goingAway = lineItemDao.getGeneratedForRun(runId).map { it.syncId }.toSet()
        val staying = items.map { it.syncId }.toSet()
        (goingAway - staying).forEach { syncId ->
            pendingDeletionDao.insert(
                PendingDeletion(syncId = syncId, tableName = "estimate_line_items")
            )
        }
        lineItemDao.replaceGeneratedForRun(runId, items)
    }
    suspend fun saveLineItem(item: EstimateLineItem): Long = lineItemDao.insert(item)
    suspend fun updateLineItem(item: EstimateLineItem) = lineItemDao.update(item)
    suspend fun deleteLineItem(item: EstimateLineItem) = lineItemDao.delete(item)

    fun observeManufacturers(): Flow<List<Manufacturer>> = manufacturerDao.observeAll()
    suspend fun getAllManufacturers(): List<Manufacturer> = manufacturerDao.getAll()
    suspend fun getEmployee(id: Long): Employee? = employeeDao.getById(id)
    suspend fun getManufacturer(id: Long): Manufacturer? = manufacturerDao.getById(id)
    suspend fun saveManufacturer(m: Manufacturer): Long =
        if (m.id == 0L) manufacturerDao.insert(m) else { manufacturerDao.update(m); m.id }
    suspend fun deleteManufacturer(m: Manufacturer) = manufacturerDao.delete(m)

    fun observePricingTiers(): Flow<List<PricingTier>> = pricingTierDao.observeAll()
    suspend fun savePricingTier(tier: PricingTier): Long =
        if (tier.id == 0L) pricingTierDao.insert(tier) else { pricingTierDao.update(tier); tier.id }
    suspend fun deletePricingTier(tier: PricingTier) = pricingTierDao.delete(tier)

    fun observePhotos(jobId: Long): Flow<List<JobPhoto>> = jobPhotoDao.observeForJob(jobId)
    suspend fun addPhoto(photo: JobPhoto): Long = jobPhotoDao.insert(photo)
    suspend fun deletePhoto(photo: JobPhoto) = jobPhotoDao.delete(photo)

    fun observeInventory(jobId: Long): Flow<List<InventoryChecklistItem>> = inventoryItemDao.observeForJob(jobId)
    suspend fun getInventory(jobId: Long): List<InventoryChecklistItem> = inventoryItemDao.getForJob(jobId)
    suspend fun addInventoryItems(items: List<InventoryChecklistItem>) = inventoryItemDao.insertAll(items)
    suspend fun addInventoryItem(item: InventoryChecklistItem): Long = inventoryItemDao.insert(item)
    suspend fun updateInventoryItem(item: InventoryChecklistItem) = inventoryItemDao.update(item)
    suspend fun deleteInventoryItem(item: InventoryChecklistItem) = inventoryItemDao.delete(item)
    suspend fun clearInventoryMaterials(jobId: Long) = inventoryItemDao.deleteByKind(jobId, InventoryKind.MATERIAL)

    fun observeEmployees(): Flow<List<Employee>> = employeeDao.observeAll()
    suspend fun getAllEmployees(): List<Employee> = employeeDao.getAll()
    suspend fun saveEmployee(e: Employee): Long =
        if (e.id == 0L) employeeDao.insert(e) else { employeeDao.update(e); e.id }
    suspend fun deleteEmployee(e: Employee) = employeeDao.delete(e)

    fun observeExpenses(jobId: Long): Flow<List<Expense>> = expenseDao.observeForJob(jobId)
    suspend fun getExpenses(jobId: Long): List<Expense> = expenseDao.getForJob(jobId)
    suspend fun getAllExpenses(): List<Expense> = expenseDao.getAll()
    suspend fun saveExpense(expense: Expense): Long = expenseDao.insert(expense)
    suspend fun deleteExpense(expense: Expense) = expenseDao.delete(expense)

    /**
     * Seeds the starter catalog and pricing tiers if they're missing.
     *
     * This runs on every app start instead of only in the database's onCreate
     * callback. That callback referenced the singleton while it was still being
     * assigned, so a null-safe call could silently skip seeding entirely -- and
     * an empty catalog makes Suggest Quantities produce nothing with no error,
     * which is exactly how it looked "broken". Checking on each start also
     * repairs installs that were left with an empty catalog by that bug.
     */
    suspend fun ensureSeedDataPresent() {
        // Clean up first: an earlier build seeded from two places at once and
        // left a second copy of every catalog item and pricing tier.
        materialDao.deleteDuplicates()
        pricingTierDao.deleteDuplicates()

        if (materialDao.count() == 0) materialDao.insertAll(SeedData.materialItems())
        if (pricingTierDao.count() == 0) pricingTierDao.insertAll(SeedData.pricingTiers())
    }

    suspend fun catalogCount(): Int = materialDao.count()

    // Suspend readers used by cloud sync, which needs a one-shot snapshot
    // rather than a Flow it would have to collect and cancel.
    suspend fun getAllMaterialItems(): List<MaterialItem> = materialDao.getAll()
    suspend fun getAllPricingTiers(): List<PricingTier> = pricingTierDao.getAll()
    suspend fun getPunchList(jobId: Long): List<PunchListItem> = punchListDao.getForJob(jobId)
    suspend fun getChangeOrders(jobId: Long): List<ChangeOrder> = changeOrderDao.getForJob(jobId)
    suspend fun getJobSteps(jobId: Long): List<JobStep> = jobStepDao.getForJob(jobId)
    suspend fun getSiteMarkers(jobId: Long): List<SiteMarker> = siteMarkerDao.getForJob(jobId)

    fun observeTimeEntries(jobId: Long): Flow<List<TimeEntry>> = timeEntryDao.observeForJob(jobId)
    fun observeRunningTimers(): Flow<List<TimeEntry>> = timeEntryDao.observeRunning()
    suspend fun getTimeEntries(jobId: Long): List<TimeEntry> = timeEntryDao.getForJob(jobId)
    suspend fun getAllTimeEntries(): List<TimeEntry> = timeEntryDao.getAll()
    suspend fun deleteTimeEntry(entry: TimeEntry) = timeEntryDao.delete(entry)
    suspend fun updateTimeEntry(entry: TimeEntry) = timeEntryDao.update(entry)

    /**
     * Starts the clock for [employeeId] on this job. Returns the existing entry
     * untouched if a shift is already running -- double-tapping Clock In must
     * never create two overlapping spans and double-bill the labor.
     */
    suspend fun clockIn(jobId: Long, employeeId: Long?, hourlyRate: Double): TimeEntry {
        timeEntryDao.runningForJob(jobId)?.let { return it }
        val entry = TimeEntry(jobId = jobId, employeeId = employeeId, hourlyRate = hourlyRate)
        val id = timeEntryDao.insert(entry)
        return entry.copy(id = id)
    }

    suspend fun clockOut(jobId: Long) {
        val running = timeEntryDao.runningForJob(jobId) ?: return
        timeEntryDao.update(running.copy(endedAt = System.currentTimeMillis()))
    }

    fun observeSiteMarkers(jobId: Long): Flow<List<SiteMarker>> = siteMarkerDao.observeForJob(jobId)
    suspend fun addSiteMarker(marker: SiteMarker): Long = siteMarkerDao.insert(marker)
    suspend fun deleteSiteMarker(marker: SiteMarker) = siteMarkerDao.delete(marker)

    fun observeChangeOrders(jobId: Long): Flow<List<ChangeOrder>> = changeOrderDao.observeForJob(jobId)
    suspend fun saveChangeOrder(order: ChangeOrder): Long = changeOrderDao.insert(order)
    suspend fun updateChangeOrder(order: ChangeOrder) = changeOrderDao.update(order)
    suspend fun deleteChangeOrder(order: ChangeOrder) = changeOrderDao.delete(order)

    fun observeJobSteps(jobId: Long): Flow<List<JobStep>> = jobStepDao.observeForJob(jobId)
    suspend fun updateJobStep(step: JobStep) = jobStepDao.update(step)

    /** Seeds the standard walkthrough + install checklists the first time a job's crew view is opened. */
    suspend fun ensureJobStepsSeeded(jobId: Long) {
        if (jobStepDao.countForJob(jobId) > 0) return
        val walkthrough = DefaultJobSteps.WALKTHROUGH.mapIndexed { index, text ->
            JobStep(jobId = jobId, kind = JobStepKind.WALKTHROUGH, description = text, sortOrder = index)
        }
        val install = DefaultJobSteps.INSTALL.mapIndexed { index, text ->
            JobStep(jobId = jobId, kind = JobStepKind.INSTALL, description = text, sortOrder = index)
        }
        jobStepDao.insertAll(walkthrough + install)
    }

    fun observePunchList(jobId: Long): Flow<List<PunchListItem>> = punchListDao.observeForJob(jobId)
    suspend fun addPunchListItem(item: PunchListItem): Long = punchListDao.insert(item)
    suspend fun updatePunchListItem(item: PunchListItem) = punchListDao.update(item)
    suspend fun deletePunchListItem(item: PunchListItem) = punchListDao.delete(item)
}
