package com.fenceestimator.app.data

/**
 * What a regenerated takeoff does to the lines already on one fence run.
 *
 * Worked out here, pure, so the rule is held to a test without a database
 * (TakeoffLineMergeTest) and both doors that regenerate -- the automatic
 * refresh when the drawing moves (TakeoffRefresher) and the Suggest
 * Quantities button (EstimateViewModel) -- apply exactly the same one.
 * [Repository.replaceAutoGeneratedLineItemsForRun] runs it inside a Room
 * transaction against the rows as they are at that moment.
 *
 * The rules, and the bug behind each:
 *
 *  - **A line somebody changed by hand is never deleted or overwritten.**
 *    Editing a line saves it with isAutoGenerated = false (EditLineItemDialog).
 *    The old replace deleted every line of the run that had a material role,
 *    edited ones included, and carried only the PRICE across -- so a quantity
 *    the owner typed snapped back to the engine's number the next time the
 *    drawing moved, or a sync echo made it look as though it had. "The price
 *    goes back after a little bit of time" was this. The cost, accepted on
 *    purpose: an edited line no longer follows the drawing. Deleting it (or
 *    retyping it) is how it moves again.
 *  - **No second line for something the person already corrected.** An
 *    edited line stands for the built line with its sync id; failing that
 *    (its id changed -- a role that starts repeating gets a width folded into
 *    its id, see EstimateEngine.deterministicSyncId), for the one built line
 *    of its role still unclaimed, or the one with its product name. The built
 *    line it stands for is not written ([claimedByEdits]). Two rows with one
 *    sync id also cannot exist locally: the cloud upsert batch refuses them
 *    with "ON CONFLICT DO UPDATE cannot affect row a second time", taking
 *    every line of the job down with it.
 *  - **Only auto-generated lines are replaced and tombstoned.** Hand-typed
 *    extras (role NONE) were never touched and still are not.
 *  - **A regenerate that lands on what is already there writes nothing.**
 *    The old comparison looked only at auto rows on one side and auto rows
 *    on the other, so an edited line (always rewritten, always different)
 *    made every refresh rewrite the run -- and with it the owner's number.
 *  - **Every sync id alive afterwards cancels its own queued delete.** Line
 *    sync ids are deterministic (run + role), so a role that dropped out of
 *    the takeoff and came back re-uses the id it had. The old code only
 *    tombstoned what was leaving; a tombstone still queued for a role that
 *    had since returned was pushed anyway, and the live line vanished on the
 *    next sync (live: 35 tombstoned role lines on live runs of five jobs).
 *
 *  - **Only what actually changed goes up, and only a returning id is
 *    revived.** A regenerate deletes and re-inserts every auto line of the
 *    run; a line that came back with exactly the content it had keeps its
 *    own [EstimateLineItem.pendingPush], and everything else is marked to
 *    push. [Plan.revive] is the ids the run did not hold before this write --
 *    a role coming back after its tombstone may already have reached the
 *    cloud. A line that was live here all along is not revived: if the cloud
 *    has it tombstoned, another phone deleted it since, and the reaper should
 *    take it here too rather than this phone quietly undoing that delete.
 *
 * Hand-typed PRICES are no longer carried by role onto freshly built lines.
 * That carry existed because the old replace threw the edited line away; now
 * the edited line itself stays, and carrying its price by role could only
 * reach a DIFFERENT line of the same role -- the 6 ft gate panel taking the
 * price somebody typed for the 4 ft one, and then counting as hand-edited
 * forever after. Supplier quotes still carry (see [withQuotedPrices]).
 *
 * NOT what the server does yet, for a run with edited lines: price-job
 * (supabase/functions/_shared/pricing/index.ts survivors, load.ts
 * buildCommitPlan) still replaces edited role lines and still carries a typed
 * price by role, and the parity mirror (PricingAdapters) mirrors the server
 * so the committed fixtures keep agreeing. The fixtures are written by the
 * Kotlin side (ParityFixtureWriter) and cannot be regenerated without a
 * gradle run, so moving the office to this rule -- index.ts, load.ts,
 * line-items.ts, PricingAdapters calling [plan], and the three fixtures with
 * edited lines -- is one commit made where the parity gate can run. For a run
 * nobody edited, the two agree: see [withQuotedPrices].
 */
object TakeoffLineMerge {

    data class Plan(
        /** Freshly built lines to write. */
        val insert: List<EstimateLineItem>,
        /** Lines somebody changed by hand. Left exactly as they are. */
        val keptEdited: List<EstimateLineItem>,
        /** The auto-generated takeoff lines on the run now. All of them give way to [insert]. */
        val replacedAuto: List<EstimateLineItem>
    ) {
        /**
         * Sync ids leaving the run for good, which need a cloud tombstone. An
         * auto row sharing an id with a kept edited row (possible only from an
         * old duplicate) is not tombstoned: that id is still alive here.
         */
        val tombstone: Set<String> =
            replacedAuto.map { it.syncId }.toSet() -
                insert.map { it.syncId }.toSet() -
                keptEdited.map { it.syncId }.toSet()

        /** Every sync id alive on the run afterwards. None may still have a delete queued. */
        val liveAfter: Set<String> = (insert + keptEdited).map { it.syncId }.toSet()

        /**
         * Sync ids this regenerate writes that the run did not hold before --
         * new lines, and roles coming back under the id they had. Only these
         * can be sitting tombstoned in the cloud from this phone's own earlier
         * removal, so only these go up with `deleted_at: null`
         * (Repository.lineItemResurrections).
         */
        val revive: Set<String> =
            insert.map { it.syncId }.toSet() - replacedAuto.map { it.syncId }.toSet() - keptEdited.map { it.syncId }.toSet()

        /**
         * True when writing would change nothing on the run. Edited lines are
         * on neither side of the comparison -- they are kept either way -- so
         * they can no longer force a rewrite.
         */
        val unchanged: Boolean =
            replacedAuto.size == insert.size &&
                replacedAuto.map(::takeoffFingerprint).toSet() == insert.map(::takeoffFingerprint).toSet()
    }

    /**
     * @param existingForRun every line currently on the run (any role, edited
     *   or not). Lines with role NONE are ignored entirely.
     * @param built what the engine produced for the run (EstimateEngine.buildLineItems).
     */
    fun plan(existingForRun: List<EstimateLineItem>, built: List<EstimateLineItem>): Plan {
        val takeoffLines = existingForRun.filter { it.role != MaterialRole.NONE }
        val edited = takeoffLines.filter { !it.isAutoGenerated }
        val auto = takeoffLines.filter { it.isAutoGenerated }

        val claimed = claimedByEdits(edited, built)
        val autoById = auto.associateBy { it.syncId }
        val insert = withQuotedPrices(built, takeoffLines)
            .filterNot { it.syncId in claimed }
            .distinctBy { it.syncId }
            .map { item ->
                // Re-inserted with exactly what it had: nothing new to send,
                // so it keeps whatever it was owed before (still waiting, or
                // already up). Anything else is a change this phone made.
                val before = autoById[item.syncId]
                val same = before != null && pushContent(before) == pushContent(item)
                item.copy(pendingPush = if (same) before!!.pendingPush else true)
            }

        return Plan(insert = insert, keptEdited = edited, replacedAuto = auto)
    }

    /**
     * The sync ids of the built lines that an edited line already stands for,
     * and which therefore must not be written beside it.
     *
     * First by sync id: an edited line with the id the build produces IS that
     * line. Then, for an edited line whose id the build no longer produces,
     * the built line of the same role that nothing has claimed yet -- when
     * there is exactly one, or else the one carrying the same product name.
     * "Exactly one" is the everyday case: a role the build makes once. The
     * product name covers the case that leaves open: a run with one gate
     * whose gate panel was edited, and a second gate of another width added,
     * builds two gate panel lines under new ids; the edited line is the old
     * gate's, and its product name picks it out. If nothing identifies it,
     * nothing is claimed -- an extra line on screen beats a gate silently
     * missing from the material order.
     */
    fun claimedByEdits(edited: List<EstimateLineItem>, built: List<EstimateLineItem>): Set<String> {
        val builtIds = built.map { it.syncId }.toSet()
        val claimed = edited.map { it.syncId }.filter { it in builtIds }.toMutableSet()
        edited.filter { it.syncId !in builtIds }.forEach { e ->
            val open = built.filter { it.role == e.role && it.syncId !in claimed }
            val pick = open.singleOrNull() ?: open.firstOrNull { it.description == e.description }
            if (pick != null) claimed += pick.syncId
        }
        return claimed
    }

    /**
     * A price read off the supplier's own quote is the most authoritative
     * number on the job, and regenerating used to throw every one of them
     * away (the Suggest button never carried them at all). Carried by role --
     * only for real roles: the column is not nullable, so testing for null
     * would sweep in every hand-typed line. `associate` keeps the last row per
     * role in the order handed in, which the caller reads sorted the way the
     * DAO sorts the estimate (sortOrder, then syncId). Carrying a quote does
     * not mark a line as hand-edited.
     *
     * By role ONLY, deliberately, because that is what price-job does
     * (pricing/line-items.ts carryOverPrices) and this is the one carry rule
     * that also reaches runs nobody edited. An earlier version of this change
     * matched the same sync id first: on a run with two gate-panel widths
     * quoted at different supplier prices the phone kept both quotes while
     * the office applied the last one to both lines, so the two priced the
     * same untouched job differently (effectiveUnitPrice reads the quote) --
     * and the parity gate could not see it, because PricingAdapters mirrors
     * the server, not this. Matching by id is the better rule; it moves with
     * the server, not ahead of it.
     */
    fun withQuotedPrices(built: List<EstimateLineItem>, existing: List<EstimateLineItem>): List<EstimateLineItem> {
        val quotedByRole = existing
            .filter { it.supplierUnitPrice != null && it.role != MaterialRole.NONE }
            .associate { it.role to it.supplierUnitPrice }
        return built.map { item ->
            val price = quotedByRole[item.role]
            if (price != null) item.copy(supplierUnitPrice = price) else item
        }
    }
}

/**
 * Everything about a line that the push carries. Two copies that agree on
 * all of it need nothing sent between them.
 */
internal fun pushContent(i: EstimateLineItem): List<Any?> = listOf(
    i.syncId, i.fenceRunId, i.sortOrder, i.role, i.description, i.quantity, i.unit,
    i.unitPrice, i.supplierUnitPrice, i.taxable, i.isAutoGenerated
)

/**
 * Whether [now] -- the row as it is after an upsert came back -- still holds
 * exactly what [sent] carried up, so its [EstimateLineItem.pendingPush] may be
 * cleared (Repository.markLineItemsPushed). Anything typed while the request
 * was in flight has not gone up, and the line must stay marked.
 */
internal fun lineItemStillAsSent(sent: EstimateLineItem, now: EstimateLineItem): Boolean =
    pushContent(sent) == pushContent(now)

/**
 * What makes two takeoff lines the same line. The sync id is part of it: a
 * line that kept its numbers but changed identity (a role that now repeats
 * gets a width folded into its id) still has to be rewritten.
 */
private fun takeoffFingerprint(i: EstimateLineItem): List<Any?> = listOf(
    i.syncId, i.role, i.description, i.quantity, i.unit,
    i.unitPrice, i.supplierUnitPrice, i.taxable, i.isAutoGenerated
)
