package com.fenceestimator.app.estimate

import com.fenceestimator.app.data.FenceRun
import com.fenceestimator.app.data.MaterialRole
import com.fenceestimator.app.data.Repository
import com.fenceestimator.app.geometry.FenceCodec
import com.fenceestimator.app.geometry.FenceGeometryEngine

/**
 * Keeps the material takeoff in step with the drawing.
 *
 * The problem this solves, in the user's words: "payments and invoices is not
 * synchronizing with the material price after I changed the drawing."
 *
 * Labour, gate charges and teardown were all computed live from the drawn
 * footage, so they moved the moment a point did. Materials did not -- posts,
 * panels, rails and concrete were frozen at whatever "Suggest Quantities"
 * produced the last time somebody pressed it. Redraw a 200 ft fence as 300 ft
 * and the estimate charged 300 ft of labour against 200 ft of material.
 *
 * That is worse than a display bug. The contract total, the deposit, the
 * payment link and the invoice all hang off that figure, so the customer was
 * quoted and billed for material nobody was buying.
 *
 * Two rules keep this from being intrusive:
 *
 *  - **Only runs that already have a takeoff are refreshed.** If nobody has
 *    pressed Suggest Quantities for a run, drawing on it does not conjure an
 *    estimate out of nowhere.
 *  - **Only auto-generated lines are replaced.** Hand-added items survive,
 *    hand-corrected prices are carried across, and roles the user removed stay
 *    removed -- the same guarantees the manual button already gives.
 */
object TakeoffRefresher {

    /**
     * Rebuilds the takeoff for [run] if it has one.
     *
     * @return true if line items were actually rewritten.
     */
    suspend fun refreshRun(repository: Repository, run: FenceRun): Boolean {
        val existing = repository.getLineItems(run.jobId).filter { it.fenceRunId == run.id }

        // Never invent an estimate for a run nobody has priced yet.
        if (existing.none { it.isAutoGenerated }) return false

        val job = repository.getJob(run.jobId) ?: return false
        val catalog = repository.getAllMaterialItems().filter { it.isActive }
        if (catalog.isEmpty()) return false

        val pixelsPerFoot = job.calibrationPixelsPerFoot ?: GRID_PIXELS_PER_FOOT

        val suggestions = EstimateEngine.suggestQuantities(
            run = run,
            pixelsPerFoot = pixelsPerFoot,
            wastePercent = job.wastePercent
        )
        val built = EstimateEngine.buildLineItems(
            jobId = run.jobId,
            fenceRunId = run.id,
            run = run,
            suggestions = suggestions,
            catalog = catalog,
            preferredManufacturerId = job.preferredManufacturerId
        )
        if (built.items.isEmpty()) return false

        // Same carry-over the manual path does: a price somebody typed by hand
        // is a decision, and regenerating must not quietly revert it to the
        // catalog figure. Matched on role, and only for real roles -- the column
        // is not nullable, so testing for null would sweep in every hand-typed
        // line that has no role at all.
        val editedPrices = existing
            .filter { !it.isAutoGenerated && it.role != MaterialRole.NONE }
            .associate { it.role to it.unitPrice }

        val finalItems = built.items.map { item ->
            val kept = editedPrices[item.role]
            if (kept != null && kept != item.unitPrice) item.copy(unitPrice = kept, isAutoGenerated = false)
            else item
        }

        repository.replaceAutoGeneratedLineItemsForRun(run.id, finalItems)
        return true
    }

    /**
     * The footage a run currently represents, used to decide whether the
     * drawing actually moved. Typed-in footage wins over the drawing, matching
     * how every other total on the job is worked out.
     */
    fun footageOf(run: FenceRun, pixelsPerFoot: Float?): Float {
        val manual = run.manualLinearFeet
        if (manual != null && manual > 0f) return manual
        val pxPerFt = pixelsPerFoot ?: GRID_PIXELS_PER_FOOT
        return FenceGeometryEngine.analyze(
            FenceCodec.decodePoints(run.pointsEncoded), pxPerFt, run.closedLoop
        ).totalLinearFeet
    }

    /** One source of truth for the grid scale, rather than a second copy to drift. */
    private val GRID_PIXELS_PER_FOOT: Float
        get() = com.fenceestimator.app.ui.survey.SurveyViewModel.PIXELS_PER_FOOT_GRID
}
