package com.fenceestimator.app.data

import com.fenceestimator.app.estimate.EstimateEngine
import com.fenceestimator.app.geometry.FenceCodec
import com.fenceestimator.app.geometry.GateMarker
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * What a regenerate does to the lines already on a run, driven the way the
 * app drives it: the engine builds the lines (EstimateEngine.buildLineItems,
 * what TakeoffRefresher and the Suggest button both call), an edit is saved
 * the way EditLineItemDialog saves one (isAutoGenerated = false), and the
 * result is applied the way the DAO applies it (delete this run's auto
 * takeoff lines, insert the plan's lines).
 *
 * Each test also works out what the OLD code produced from the same rows --
 * delete every roled line, carry only the typed price by role, compare auto
 * rows only, tombstone goingAway - staying -- and asserts it differs, so a
 * pass here is the rule and not the fixture.
 */
class TakeoffLineMergeTest {

    private val catalog = listOf(
        MaterialItem(category = MaterialCategory.POST, role = MaterialRole.LINE_POST, fenceType = FenceType.VINYL, name = "Post", unitPrice = 16.56),
        MaterialItem(category = MaterialCategory.POST, role = MaterialRole.END_POST, fenceType = FenceType.VINYL, name = "End post", unitPrice = 30.0),
        MaterialItem(category = MaterialCategory.PANEL, role = MaterialRole.PANEL, fenceType = FenceType.VINYL, name = "Panel 6", unitPrice = 52.35, coversFt = 6f),
        MaterialItem(category = MaterialCategory.GATE, role = MaterialRole.GATE_PANEL, fenceType = FenceType.VINYL, name = "Gate 4ft", unitPrice = 200.0, coversFt = 4f),
        MaterialItem(category = MaterialCategory.GATE, role = MaterialRole.GATE_PANEL, fenceType = FenceType.VINYL, name = "Gate 6ft", unitPrice = 260.0, coversFt = 6f),
        MaterialItem(category = MaterialCategory.HARDWARE, role = MaterialRole.HINGE_SET, fenceType = FenceType.VINYL, name = "Hinges", unitPrice = 30.0),
        MaterialItem(category = MaterialCategory.HARDWARE, role = MaterialRole.LATCH, fenceType = FenceType.VINYL, name = "Latch", unitPrice = 25.87)
    )

    private val runSyncId = "5b0c1f7e-0000-4000-8000-000000000001"

    private fun run(feet: Float, gates: List<GateMarker> = emptyList()) = FenceRun(
        id = 7, syncId = runSyncId, jobId = 1, fenceType = FenceType.VINYL,
        manualLinearFeet = feet, gatesEncoded = FenceCodec.encodeGates(gates),
        panelWidthFt = 6f, postSpacingFt = 6f, concreteBagsPerPost = 1f
    )

    /** What the Suggest button and the refresh hand the repository. */
    private fun build(r: FenceRun): List<EstimateLineItem> =
        EstimateEngine.buildLineItems(
            jobId = 1, fenceRunId = r.id, run = r,
            suggestions = EstimateEngine.suggestQuantities(r, pixelsPerFoot = 20f),
            catalog = catalog, preferredManufacturerId = null
        ).items

    /** What EstimateLineItemDao.replaceAutoGeneratedForRun leaves on the job. */
    private fun apply(existing: List<EstimateLineItem>, plan: TakeoffLineMerge.Plan): List<EstimateLineItem> =
        existing.filterNot { it.fenceRunId == 7L && it.role != MaterialRole.NONE && it.isAutoGenerated } +
            plan.insert

    /** The old replace: every roled line of the run deleted, the typed price carried by role. */
    private fun oldReplace(existing: List<EstimateLineItem>, built: List<EstimateLineItem>): List<EstimateLineItem> {
        val editedPrices = existing
            .filter { !it.isAutoGenerated && it.role != MaterialRole.NONE }
            .associate { it.role to it.unitPrice }
        val carried = built.map { item ->
            val kept = editedPrices[item.role]
            if (kept != null && kept != item.unitPrice) item.copy(unitPrice = kept, isAutoGenerated = false) else item
        }
        return existing.filter { it.role == MaterialRole.NONE } + carried
    }

    /** Saved the way EditLineItemDialog saves an edit. */
    private fun edited(line: EstimateLineItem, quantity: Double = line.quantity, price: Double = line.unitPrice) =
        line.copy(quantity = quantity, unitPrice = price, isAutoGenerated = false)

    private fun List<EstimateLineItem>.byRole(role: MaterialRole) = filter { it.role == role }

    @Test
    fun `a quantity typed by hand survives the drawing moving`() {
        val first = build(run(100f))
        val panel = first.single { it.role == MaterialRole.PANEL }
        val onPhone = first.map { if (it.syncId == panel.syncId) edited(it, quantity = 18.0) else it }

        // 120 ft: the engine now wants 20 panels.
        val rebuilt = build(run(120f))
        assertEquals(20.0, rebuilt.single { it.role == MaterialRole.PANEL }.quantity, 0.0)

        val after = apply(onPhone, TakeoffLineMerge.plan(onPhone, rebuilt))
        val panels = after.byRole(MaterialRole.PANEL)
        assertEquals("exactly one panel line", 1, panels.size)
        assertEquals("the typed 18 stands", 18.0, panels.single().quantity, 0.0)
        assertFalse(panels.single().isAutoGenerated)
        assertEquals("no two lines may share a sync id", after.size, after.map { it.syncId }.toSet().size)
        // Everything nobody touched still follows the drawing.
        assertEquals(
            rebuilt.single { it.role == MaterialRole.LINE_POST }.quantity,
            after.single { it.role == MaterialRole.LINE_POST }.quantity, 0.0
        )

        // Planted failure: the old replace threw the typed 18 away.
        val old = oldReplace(onPhone, rebuilt).byRole(MaterialRole.PANEL)
        assertNotEquals(18.0, old.single().quantity, 0.0)
    }

    @Test
    fun `an edited line cannot force a rewrite when nothing moved`() {
        val first = build(run(100f))
        val panel = first.single { it.role == MaterialRole.PANEL }
        // Only the quantity was changed, so the price still matches the catalog.
        val onPhone = first.map { if (it.syncId == panel.syncId) edited(it, quantity = 18.0) else it }

        val plan = TakeoffLineMerge.plan(onPhone, build(run(100f)))
        assertTrue("the same drawing rebuilt must write nothing", plan.unchanged)
        assertTrue(plan.tombstone.isEmpty())

        // Planted failure: the old comparison (auto rows vs auto rows after the
        // price carry) saw different sizes and rewrote the run -- and the 18.
        val existingAuto = onPhone.filter { it.isAutoGenerated }
        val oldFinal = oldReplace(onPhone, build(run(100f))).filter { it.role != MaterialRole.NONE }
        val oldUnchanged = existingAuto.size == oldFinal.count { it.isAutoGenerated }
        assertFalse(oldUnchanged)
    }

    @Test
    fun `a role that leaves and comes back cancels its own queued delete and is revived`() {
        val gate = GateMarker(0f, 0f, 4f)
        val withGate = build(run(100f, listOf(gate)))
        val gateIds = withGate.filter { it.role in setOf(MaterialRole.GATE_PANEL, MaterialRole.HINGE_SET, MaterialRole.LATCH) }
            .map { it.syncId }.toSet()
        assertEquals(3, gateIds.size)

        // The gate is removed: its lines go, and their tombstones are queued.
        val plan1 = TakeoffLineMerge.plan(withGate, build(run(100f)))
        assertEquals(gateIds, plan1.tombstone)
        val afterRemove = apply(withGate, plan1)
        val queued = plan1.tombstone.toMutableSet()

        // Put straight back, same width: the same deterministic sync ids.
        val rebuilt = build(run(100f, listOf(gate)))
        val plan2 = TakeoffLineMerge.plan(afterRemove, rebuilt)
        assertEquals("exactly the returning ids are revived", gateIds, plan2.revive)
        queued -= plan2.liveAfter   // what Repository does inside the same transaction
        assertTrue("a returned role must not keep its tombstone queued", queued.isEmpty())

        // If those tombstones already reached the cloud, the reaper must spare
        // the lines this regenerate wrote, and the push revives them.
        assertTrue(LineItemResurrections.reapable(plan1.tombstone, plan2.revive).isEmpty())

        // Planted failure: the old code only ever added goingAway - staying and
        // never removed anything, so all three were still queued -- and the
        // reaper with nothing to spare deleted all three.
        val oldQueued = plan1.tombstone.toMutableSet().apply {
            addAll(afterRemove.filter { it.role != MaterialRole.NONE }.map { it.syncId } - rebuilt.map { it.syncId }.toSet())
        }
        assertEquals(gateIds, oldQueued)
        assertEquals(gateIds, LineItemResurrections.reapable(plan1.tombstone, emptySet()).toSet())
    }

    @Test
    fun `an edited gate panel stays the old gate's when a second width is added`() {
        val four = GateMarker(0f, 0f, 4f)
        val first = build(run(100f, listOf(four)))
        val gatePanel = first.single { it.role == MaterialRole.GATE_PANEL }
        assertEquals("Gate 4ft", gatePanel.description)
        val onPhone = first.map { if (it.syncId == gatePanel.syncId) edited(it, price = 185.0) else it }

        val rebuilt = build(run(100f, listOf(four, GateMarker(50f, 0f, 6f))))
        val builtPanels = rebuilt.byRole(MaterialRole.GATE_PANEL)
        assertEquals(2, builtPanels.size)
        assertTrue("a repeated role gets new ids", builtPanels.none { it.syncId == gatePanel.syncId })

        val after = apply(onPhone, TakeoffLineMerge.plan(onPhone, rebuilt))
        val panels = after.byRole(MaterialRole.GATE_PANEL)
        assertEquals("the edited 4 ft line and a new 6 ft line", 2, panels.size)
        assertEquals(185.0, panels.single { it.description == "Gate 4ft" }.unitPrice, 0.0)
        val six = panels.single { it.description == "Gate 6ft" }
        // No typed price carried across widths, and the new line still follows the drawing.
        assertEquals(260.0, six.unitPrice, 0.0)
        assertTrue(six.isAutoGenerated)

        // Planted failure: claiming by sync id alone left the old gate's panel
        // twice -- the edited line plus a fresh 4 ft line beside it.
        val bySyncIdOnly = onPhone.filter { !it.isAutoGenerated } +
            rebuilt.filterNot { b -> onPhone.any { !it.isAutoGenerated && it.syncId == b.syncId } }
        assertEquals(3, bySyncIdOnly.byRole(MaterialRole.GATE_PANEL).size)
        // And the old carry put the 4 ft price on the 6 ft gate.
        assertEquals(185.0, oldReplace(onPhone, rebuilt).single { it.description == "Gate 6ft" }.unitPrice, 0.0)
    }

    @Test
    fun `a leftover duplicate of an edited role is tombstoned, not kept beside it`() {
        val first = build(run(100f))
        val post = first.single { it.role == MaterialRole.LINE_POST }
        // What the delete-edited-lines era could leave: the user's edited line
        // under an older id, and an auto line under the current one.
        val legacyEdited = post.copy(id = 99, syncId = "legacy-line-post", quantity = 12.0, isAutoGenerated = false)
        val onPhone = first + legacyEdited

        val plan = TakeoffLineMerge.plan(onPhone, build(run(100f)))
        val after = apply(onPhone, plan)
        assertEquals(listOf(12.0), after.byRole(MaterialRole.LINE_POST).map { it.quantity })
        assertTrue(post.syncId in plan.tombstone)
        assertFalse("the edited line's own id is alive", "legacy-line-post" in plan.tombstone)
    }

    @Test
    fun `a supplier quote carries over and does not mark the line as edited`() {
        val first = build(run(100f))
        val onPhone = first.map { if (it.role == MaterialRole.PANEL) it.copy(supplierUnitPrice = 49.0) else it }

        val plan = TakeoffLineMerge.plan(onPhone, build(run(120f)))
        val panel = plan.insert.single { it.role == MaterialRole.PANEL }
        assertEquals(49.0, panel.supplierUnitPrice!!, 0.0)
        assertTrue(panel.isAutoGenerated)
    }

    @Test
    fun `hand-typed extras are never part of the merge`() {
        val first = build(run(100f))
        val extra = EstimateLineItem(
            id = 50, syncId = "extra", jobId = 1, fenceRunId = 7, description = "Haul away",
            quantity = 1.0, unitPrice = 90.0, role = MaterialRole.NONE, isAutoGenerated = false
        )
        val onPhone = first + extra

        val plan = TakeoffLineMerge.plan(onPhone, build(run(120f)))
        assertFalse(plan.keptEdited.any { it.syncId == "extra" })
        assertFalse("extra" in plan.tombstone)
        assertTrue(apply(onPhone, plan).any { it.syncId == "extra" })
    }

    @Test
    fun `a line that was live on the run all along is not revived`() {
        // The drawing moved: every line is re-inserted, none of them new.
        val first = build(run(100f))
        val plan = TakeoffLineMerge.plan(first, build(run(120f)))
        assertTrue("nothing here came back from a tombstone", plan.revive.isEmpty())
        // Planted failure: reviving every id written -- the first version --
        // would send deleted_at: null for a line another phone deleted after
        // this one last looked, undoing that delete.
        assertTrue(plan.insert.map { it.syncId }.toSet().isNotEmpty())
        assertNotEquals(plan.revive, plan.insert.map { it.syncId }.toSet())
    }

    @Test
    fun `only the lines a rebuild changed are marked to go up`() {
        // Uploaded already: nothing owed.
        val first = build(run(100f)).map { it.copy(pendingPush = false) }
        // 120 ft: the panels and line posts move; the two end posts do not.
        val plan = TakeoffLineMerge.plan(first, build(run(120f)))
        val before = first.associateBy { it.syncId }
        plan.insert.forEach { line ->
            val was = before[line.syncId]
            val same = was != null && was.quantity == line.quantity && was.unitPrice == line.unitPrice &&
                was.description == line.description && was.sortOrder == line.sortOrder
            assertEquals("${line.description}: marked only if it changed", !same, line.pendingPush)
        }
        assertTrue("something did change", plan.insert.any { it.pendingPush })
        assertTrue("and something did not", plan.insert.any { !it.pendingPush })
        // Planted failure: marking every re-inserted line would push the whole
        // run on every refresh -- the "every line on every pass" the mark exists to end.
        assertNotEquals(plan.insert.size, plan.insert.count { it.pendingPush })
    }

    @Test
    fun `a line still waiting to go up stays waiting when it comes back unchanged`() {
        val first = build(run(100f)).map { it.copy(pendingPush = true) }
        val plan = TakeoffLineMerge.plan(first, build(run(100f)))
        // The same drawing: nothing is rewritten at all...
        assertTrue(plan.unchanged)
        // ...and a rewrite forced by one change keeps the others' marks.
        val plan2 = TakeoffLineMerge.plan(first, build(run(120f)))
        assertTrue(plan2.insert.all { it.pendingPush })
    }

    @Test
    fun `a supplier quote is carried by role, as price-job carries it`() {
        // Two gate widths, quoted at different supplier prices.
        val two = build(run(100f, listOf(GateMarker(0f, 0f, 4f), GateMarker(50f, 0f, 6f))))
        val panels = two.byRole(MaterialRole.GATE_PANEL)
        assertEquals(2, panels.size)
        val quoted = two.map {
            when (it.syncId) {
                panels[0].syncId -> it.copy(supplierUnitPrice = 190.0)
                panels[1].syncId -> it.copy(supplierUnitPrice = 250.0)
                else -> it
            }
        }
        val plan = TakeoffLineMerge.plan(quoted, build(run(110f, listOf(GateMarker(0f, 0f, 4f), GateMarker(50f, 0f, 6f)))))
        val carried = plan.insert.byRole(MaterialRole.GATE_PANEL).map { it.supplierUnitPrice }
        // pricing/line-items.ts carryOverPrices: by role, the last row per
        // role in the estimate's order. The office and the phone must price
        // an untouched job the same way.
        val lastByRole = quoted.filter { it.role == MaterialRole.GATE_PANEL }.last().supplierUnitPrice
        assertEquals(listOf(lastByRole, lastByRole), carried)
        // Planted failure: matching by sync id first (the first version of
        // this change) kept both quotes -- a different total from price-job's
        // for a job nobody edited.
        val byIdFirst = plan.insert.byRole(MaterialRole.GATE_PANEL).map { line ->
            quoted.firstOrNull { it.syncId == line.syncId }?.supplierUnitPrice
        }
        assertNotEquals(carried, byIdFirst)
    }

    @Test
    fun `a pushed line whose row moved while the upsert was in flight stays marked`() {
        val sent = build(run(100f)).first().copy(pendingPush = true)
        assertTrue(lineItemStillAsSent(sent, sent))
        // Typed while the request was out: not what went up.
        val typed = sent.copy(quantity = sent.quantity + 3)
        assertFalse(lineItemStillAsSent(sent, typed))
        // The mark itself, and the Room id, are not content.
        assertTrue(lineItemStillAsSent(sent, sent.copy(pendingPush = false, id = 999)))
    }
}
