package com.fenceestimator.app.cloud

import com.fenceestimator.app.data.EstimateLineItem
import com.fenceestimator.app.data.MaterialRole
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.jsonObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * What a line-item push actually puts on the wire, through [cloudJson] --
 * the Json the Supabase client encodes every upsert with.
 *
 * A line this phone regenerated under a sync id the cloud holds tombstoned
 * has to go up with an explicit `"deleted_at": null`, or the upsert rewrites
 * a deleted row's quantity and price and leaves it deleted (Woody: LINE_POST
 * and PANEL rewritten while tombstoned, $3,963.44 hidden). Every OTHER line
 * must carry no deleted_at at all, or an ordinary push undoes every delete
 * another phone made.
 */
class LineItemPushTest {

    private fun line(syncId: String) = CloudLineItem(
        companyId = "co", syncId = syncId, jobSyncId = "job", fenceRunSyncId = "run",
        description = "Panel 6", quantity = 17.0, unitPrice = 52.35, role = "PANEL", autoGenerated = true
    )

    private fun wire(rows: List<CloudLineItem>): JsonArray =
        cloudJson.encodeToJsonElement(ListSerializer(CloudLineItem.serializer()), rows) as JsonArray

    @Test
    fun `a revived line says deleted_at null and an ordinary line says nothing about it`() {
        val (plain, reviving) = reviveLineItems(listOf(line("a"), line("b")), revive = setOf("b"))
        assertEquals(listOf("a"), plain.map { it.syncId })
        assertEquals(listOf("b"), reviving.map { it.syncId })

        val revived = wire(reviving).single().jsonObject
        assertTrue("the key must be present", revived.containsKey("deleted_at"))
        assertEquals(JsonNull, revived["deleted_at"])
        assertEquals(JsonPrimitive(""), revived["deleted_by"])

        val ordinary = wire(plain).single().jsonObject
        assertFalse(ordinary.containsKey("deleted_at"))
        assertFalse(ordinary.containsKey("deleted_by"))
    }

    /** The obvious field, which is what CloudLineItem would have had. */
    @Serializable
    private data class NaiveRevive(
        @SerialName("sync_id") val syncId: String,
        @SerialName("deleted_at") val deletedAt: String? = null
    )

    // Planted failure: a plain nullable field set to null is dropped by
    // explicitNulls = false -- the upsert would never mention deleted_at, and
    // the tombstone would stay exactly where it was.
    @Test
    fun `a nullable String would never send the null`() {
        val body = cloudJson.encodeToJsonElement(NaiveRevive.serializer(), NaiveRevive("b")).jsonObject
        assertFalse(body.containsKey("deleted_at"))
    }

    @Test
    fun `revivals and ordinary lines never share a batch`() {
        val (plain, reviving) = reviveLineItems(listOf(line("a"), line("b"), line("c")), revive = setOf("b"))
        // Every row in a batch carries the same keys, so PostgREST can never
        // turn a missing key on one row into an explicit null.
        assertTrue(wire(plain).all { !it.jsonObject.containsKey("deleted_at") })
        assertTrue(wire(reviving).all { it.jsonObject.containsKey("deleted_at") })
        assertEquals(setOf("a", "c"), plain.map { it.syncId }.toSet())
    }

    @Test
    fun `nothing waiting means nothing is revived`() {
        val (plain, reviving) = reviveLineItems(listOf(line("a")), revive = emptySet())
        assertEquals(1, plain.size)
        assertTrue(reviving.isEmpty())
    }

    @Test
    fun `pulled rows still decode with or without deleted_at`() {
        val live = cloudJson.decodeFromString(
            CloudLineItem.serializer(),
            """{"company_id":"co","sync_id":"a","job_sync_id":"job","deleted_at":null,"deleted_by":""}"""
        )
        assertEquals("a", live.syncId)
        // The crew view carries neither column.
        val crew = cloudJson.decodeFromString(
            CloudLineItem.serializer(),
            """{"company_id":"co","sync_id":"a","job_sync_id":"job"}"""
        )
        assertNull(crew.deletedAt)
        assertNull(crew.deletedBy)
        // PricingDrift decodes tombstoned rows through the same class.
        val tombstoned = cloudJson.decodeFromString(
            CloudLineItem.serializer(),
            """{"company_id":"co","sync_id":"a","job_sync_id":"job","deleted_at":"2026-08-24T00:30:00+00:00","deleted_by":"x"}"""
        )
        assertEquals(JsonPrimitive("2026-08-24T00:30:00+00:00"), tombstoned.deletedAt)
    }

    @Test
    fun `the pull does not put back a line this phone has a delete queued for`() {
        val cloud = listOf(line("kept"), line("deleted-here"))
        val applied = lineItemsToApply(cloud, queuedDeletes = setOf("deleted-here"))
        assertEquals(listOf("kept"), applied.map { it.syncId })

        // Planted failure: the old pull wrote every cloud row it did not hold
        // locally -- including the one just deleted here, whose tombstone a
        // MANAGER phone can never land.
        assertTrue(cloud.any { it.syncId == "deleted-here" })
    }

    // ---- only lines changed here go up, and the pull leaves those alone ----

    private fun local(pending: Boolean) = EstimateLineItem(
        syncId = "a", jobId = 1, fenceRunId = 3, description = "Panel 6", quantity = 18.0,
        unitPrice = 52.35, role = MaterialRole.PANEL, isAutoGenerated = false, pendingPush = pending
    )

    @Test
    fun `the pull does not write over a line changed here and not yet up`() {
        assertFalse("a typed 18 waiting to go up is kept", pullMayWriteLine(local(pending = true)))
        assertTrue("a line the cloud already has takes the cloud's copy", pullMayWriteLine(local(pending = false)))
        assertTrue("a line this phone does not hold is inserted", pullMayWriteLine(null))
        // Planted failure: the old pull wrote every cloud row over its local
        // line unconditionally -- the typed 18 reverted the same second a
        // failed push left it behind.
        val oldPull: (EstimateLineItem?) -> Boolean = { true }
        assertNotEquals(oldPull(local(pending = true)), pullMayWriteLine(local(pending = true)))
    }

    @Test
    fun `a local line goes up with its run and its supplier quote`() {
        val row = local(pending = true).copy(supplierUnitPrice = 49.0).toCloud("co", "job", mapOf(3L to "run-3"))
        assertEquals("run-3", row.fenceRunSyncId)
        assertEquals(49.0, row.supplierUnitPrice!!, 0.0)
        assertEquals("PANEL", row.role)
        assertFalse(row.autoGenerated)
        // The mark is the phone's bookkeeping; nothing about it is sent.
        val wire = cloudJson.encodeToJsonElement(CloudLineItem.serializer(), row).jsonObject
        assertFalse(wire.keys.any { it.contains("pending") })
    }

    // ---- change orders inside an accepted price ----

    private fun order(syncId: String, marked: Boolean?) =
        CloudChangeOrder(companyId = "co", syncId = syncId, jobSyncId = "job", additionalCost = 900.0, inAcceptedTotal = marked)

    @Test
    fun `a marked order goes up in a batch of its own, and an unmarked one says nothing`() {
        val (plain, marked) = splitChangeOrdersByAcceptance(listOf(order("a", true), order("b", null), order("c", false)))
        assertEquals(listOf("a"), marked.map { it.syncId })
        assertEquals(listOf("b", "c"), plain.map { it.syncId })
        val plainWire = cloudJson.encodeToJsonElement(ListSerializer(CloudChangeOrder.serializer()), plain) as JsonArray
        assertTrue("an ordinary push never names the column", plainWire.all { !it.jsonObject.containsKey("in_accepted_total") })
        val markedWire = cloudJson.encodeToJsonElement(ListSerializer(CloudChangeOrder.serializer()), marked) as JsonArray
        assertEquals(JsonPrimitive(true), markedWire.single().jsonObject["in_accepted_total"])
        // Planted failure: one batch -- every row named by any row goes up on
        // all of them, so the unmarked rows would carry an explicit null (and
        // a database without the column would refuse the whole batch).
        val mixed = cloudJson.encodeToJsonElement(
            ListSerializer(CloudChangeOrder.serializer()), listOf(order("a", true), order("b", null))
        ) as JsonArray
        assertNotEquals(mixed.map { it.jsonObject.keys }.toSet().size, 1)
    }
}
